import { lazy, Suspense, useState } from 'react';
import { router, Deferred } from '@inertiajs/react';
import AppLayout from '../Layouts/AppLayout';
import BrowsePanel, { BrowsePanelSkeleton } from '../Components/panels/BrowsePanel';
import UploadPanel from '../Components/panels/UploadPanel';
import AccessPanel from '../Components/panels/AccessPanel';
import SettingsPanel from '../Components/panels/SettingsPanel';
import NotificationsPanel from '../Components/panels/NotificationsPanel';
import ReportsPanel from '../Components/panels/ReportsPanel';
import IntegrationsPanel from '../Components/panels/IntegrationsPanel';
import UserGuidePanel from '../Components/panels/UserGuidePanel';
import FloatingActionBar from '../Components/ui/FloatingActionBar';
import Toast from '../Components/ui/Toast';
import PanelErrorBoundary from '../Components/ui/PanelErrorBoundary';
import type { AccessLevel, AccessPolicy, DashboardProps, MediaFile, SavedSearch, ToastItem, UserRole } from '../types';

const PreviewModal=lazy(()=>import('../Components/modals/PreviewModal'));
const CategoryModal=lazy(()=>import('../Components/modals/CategoryModal'));
const BulkEditModal=lazy(()=>import('../Components/modals/BulkEditModal'));
type ActiveTab='browse-panel'|'upload-panel'|'access-panel'|'settings-panel'|'notifications-panel'|'reports-panel'|'integrations-panel'|'guide-panel';
type PanelSlug='browse'|'upload'|'access'|'settings'|'notifications'|'reports'|'integrations'|'guide';
const PANEL_TO_TAB:Record<PanelSlug,ActiveTab>={browse:'browse-panel',upload:'upload-panel',access:'access-panel',settings:'settings-panel',notifications:'notifications-panel',reports:'reports-panel',integrations:'integrations-panel',guide:'guide-panel'};
const TAB_TO_PANEL:Record<ActiveTab,PanelSlug>={
 'browse-panel':'browse','upload-panel':'upload','access-panel':'access','settings-panel':'settings','notifications-panel':'notifications','reports-panel':'reports','integrations-panel':'integrations','guide-panel':'guide'
};
const activeTabFromPanel=(panel?:string):ActiveTab=>PANEL_TO_TAB[(Object.hasOwn(PANEL_TO_TAB,panel||'')?panel:'browse') as PanelSlug];
const csrf=()=>document.querySelector('meta[name="csrf-token"]')?.getAttribute('content')||'';

async function jsonRequest(url:string,method:string,body:Record<string,unknown>={}){
 const r=await fetch(url,{method,headers:{'X-CSRF-TOKEN':csrf(),'Content-Type':'application/json','Accept':'application/json'},body:method==='GET'?undefined:JSON.stringify(body)});
 const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.message||`HTTP ${r.status}`);return data;
}

export default function Dashboard({categories,departments,appVersion,files,users,organizationUnits,permissionSets,portalRoles,userGroups,pageAccess,networkPolicySummary,approvalDelegations,securityAuthSettings,accessMaturitySettings,filterOwners,savedSearches,quickViewCounts,fontFamilies,appearanceSettings,searchSettings,masterData,metadataSettings,notificationSettings,notificationPreferences,notificationEscalation,uploadSettings,integrationConnections,sourceConnections,integrationHealthSummary,backupSettings,backupRuns,restoreVerifications,backupStatus,readinessData,featureCompletionSettings,userGuideAccess,stats,currentUser,simulatedRole,filters,accessRequests,notifications,unreadNotifications}:DashboardProps){
 const requestedTab=activeTabFromPanel(filters.panel);
 const defaultSimPages=simulatedRole==='viewer'?{browse:true,upload:false,access:true,reports:true,integrations:false,guide:true,settings:false}:simulatedRole==='department-operator'?{browse:true,upload:true,access:true,reports:true,integrations:false,guide:true,settings:false}:simulatedRole==='department-admin'?{browse:true,upload:true,access:true,reports:true,integrations:true,guide:true,settings:true}:pageAccess;
 const effectivePageAccess=currentUser.role==='super-admin'&&simulatedRole!=='super-admin'?defaultSimPages:pageAccess;
 const tabPage:Partial<Record<ActiveTab,string>>={'browse-panel':'browse','upload-panel':'upload','access-panel':'access','reports-panel':'reports','integrations-panel':'integrations','guide-panel':'guide','settings-panel':'settings'};
 const requestedPage=tabPage[requestedTab];
 const activeTab=(requestedTab==='guide-panel'&&!userGuideAccess.can_view)||(requestedPage&&!effectivePageAccess[requestedPage as keyof typeof effectivePageAccess])?'browse-panel':requestedTab;
 const [selectedFiles,setSelectedFiles]=useState<Set<number>>(new Set()),[previewFile,setPreviewFile]=useState<MediaFile|null>(null),[showCategoryModal,setShowCategoryModal]=useState(false),[showBulkEdit,setShowBulkEdit]=useState(false),[categoryParent,setCategoryParent]=useState<number|null>(null),[toasts,setToasts]=useState<ToastItem[]>([]);
 const toast=(message:string,type:'success'|'error')=>{const id=crypto.randomUUID();setToasts(x=>[...x,{id,message,type}]);setTimeout(()=>setToasts(x=>x.filter(t=>t.id!==id)),4000)};
 const canUpload=simulatedRole!=='viewer'&&Boolean(effectivePageAccess.upload),canDelete=['super-admin','department-admin'].includes(simulatedRole),canBulkEdit=['super-admin','department-admin','department-operator'].includes(simulatedRole),canManageRoles=simulatedRole==='super-admin',canConfigCategories=['super-admin','department-admin'].includes(simulatedRole),canManageDepartments=simulatedRole==='super-admin',canViewAccess=Boolean(effectivePageAccess.access),canViewReports=Boolean(effectivePageAccess.reports),canViewIntegrations=['super-admin','department-admin'].includes(simulatedRole)&&Boolean(effectivePageAccess.integrations),canViewUserGuide=userGuideAccess.can_view&&Boolean(effectivePageAccess.guide),canViewSettings=['super-admin','department-admin'].includes(simulatedRole)&&Boolean(effectivePageAccess.settings);
 const roleChange=(role:UserRole)=>router.post('/simulate-role',{role},{preserveState:true,onSuccess:()=>toast(`Switched to ${role} view`,'success'),onError:()=>toast('Failed to switch role','error')});
 const switchTab=(tab:ActiveTab)=>{const panel=TAB_TO_PANEL[tab];router.get('/',{...filters,panel:panel==='browse'?undefined:panel},{preserveState:true,preserveScroll:true,only:['filters']});};
 const go=(next:Record<string,unknown>,only=['files','filters','stats'] as string[])=>router.get('/',{...filters,...next,panel:undefined,page:1},{preserveState:true,preserveScroll:true,only});
 const fileList=files?.data??[];
 const toggle=(id:number)=>setSelectedFiles(x=>{const n=new Set(x);n.has(id)?n.delete(id):n.add(id);return n});
 const selectAll=()=>setSelectedFiles(selectedFiles.size===fileList.length?new Set():new Set(fileList.map(f=>f.id)));
 const handleDelete=(fileId?:number)=>{const ids=fileId?[fileId]:Array.from(selectedFiles);if(!ids.length||!confirm(`Move ${ids.length} file(s) to Recycle Bin? Files can be restored later.`))return;router.delete('/files/bulk-delete',{data:{ids},preserveState:true,onSuccess:()=>{setSelectedFiles(new Set());setPreviewFile(null);toast('Files moved to Recycle Bin','success')},onError:()=>toast('Delete failed','error')})};
 const handleDownload=(id:number)=>{const f=(previewFile?.id===id?previewFile:fileList.find(x=>x.id===id));if(!f?.can_download)return toast('Download is not permitted with your current access.','error');const url=f.temporary_download_url||f.download_url;if(!url)return toast('Download URL unavailable','error');window.location.href=url};
 const handleDownloadZip=()=>{if(!selectedFiles.size)return;const selected=fileList.filter(f=>selectedFiles.has(f.id));const blocked=selected.filter(f=>!f.can_download);if(blocked.length)return toast(`${blocked.length} selected file(s) are not downloadable with your current access.`,'error');const form=document.createElement('form');form.method='POST';form.action='/files/bulk-download';form.style.display='none';const token=document.createElement('input');token.type='hidden';token.name='_token';token.value=csrf();form.appendChild(token);Array.from(selectedFiles).forEach(id=>{const input=document.createElement('input');input.type='hidden';input.name='ids[]';input.value=String(id);form.appendChild(input)});document.body.appendChild(form);form.submit();form.remove();toast('Authorized server-side ZIP download requested.','success')};
 const openCategory=(parent:number|null)=>{setCategoryParent(parent);setShowCategoryModal(true)};
 const requestAccess=async(file:MediaFile,reason:string,level:AccessLevel)=>{try{await jsonRequest(`/files/${file.id}/access-request`,'POST',{reason,access_level:level});toast('Access request submitted.','success');setPreviewFile(null);router.reload({only:['files','accessRequests','notifications','unreadNotifications']});return true}catch(e){toast(e instanceof Error?e.message:'Access request failed.','error');return false}};
 const updatePolicy=async(file:MediaFile,policy:AccessPolicy,downloadAllowed:boolean)=>{try{await jsonRequest(`/files/${file.id}/access-policy`,'PATCH',{access_policy:policy,download_allowed:downloadAllowed});toast('Access policy updated.','success');setPreviewFile(null);router.reload({only:['files','stats','accessRequests']});return true}catch(e){toast(e instanceof Error?e.message:'Could not update access policy.','error');return false}};
 const openPreview=async(file:MediaFile)=>{setPreviewFile(file);try{await jsonRequest(`/files/${file.id}/recent`,'POST');router.reload({only:['quickViewCounts']})}catch{/* viewing must not fail because recent-history recording failed */}};
 const toggleFavorite=async(file:MediaFile)=>{try{const r=await jsonRequest(`/files/${file.id}/favorite`,'POST');toast(r.favorite?'Added to favorites':'Removed from favorites','success');router.reload({only:['files','quickViewCounts']})}catch(e){toast(e instanceof Error?e.message:'Could not update favorite','error')}};
 const saveSearch=async(name:string)=>{const payload={...filters};delete (payload as Record<string,unknown>).page;try{await jsonRequest('/searches/saved','POST',{name,filters:payload});toast(`Saved search “${name}”`,'success');router.reload({only:['savedSearches']})}catch(e){toast(e instanceof Error?e.message:'Could not save search','error')}};
 const applySavedSearch=(saved:SavedSearch)=>router.get('/',{...saved.filters,panel:undefined,page:1},{preserveState:true,preserveScroll:true});
 const deleteSavedSearch=async(saved:SavedSearch)=>{if(!confirm(`Delete saved search “${saved.name}”?`))return;try{await jsonRequest(`/searches/saved/${saved.id}`,'DELETE');toast('Saved search deleted','success');router.reload({only:['savedSearches']})}catch(e){toast(e instanceof Error?e.message:'Could not delete saved search','error')}};

 return <><AppLayout activeTab={activeTab} onTabSwitch={switchTab} categories={categories} simulatedRole={simulatedRole} currentUser={currentUser} onRoleChange={roleChange} initialSearch={filters.search||''} onSearch={q=>go({search:q||undefined,sort:q&&searchSettings.best_match_sort?'best':filters.sort})} onCategorySelect={(c,s)=>go({category_id:c??undefined,subcategory_id:s??undefined,quick_view:undefined})} onAddCategory={openCategory} canUpload={canUpload} canManageRoles={canManageRoles} canViewAccess={canViewAccess} canViewReports={canViewReports} canConfigCategories={canConfigCategories} canViewSettings={canViewSettings} canViewIntegrations={canViewIntegrations} canViewUserGuide={canViewUserGuide} selectedCategoryId={filters.category_id?Number(filters.category_id):null} selectedSubcategoryId={filters.subcategory_id?Number(filters.subcategory_id):null} searchSettings={searchSettings} notifications={notifications} unreadNotifications={unreadNotifications}>
  <PanelErrorBoundary panelName="Browse Files" resetKey={activeTab}><Deferred data={['files','stats']} fallback={<BrowsePanelSkeleton active={activeTab==='browse-panel'}/>}><BrowsePanel active={activeTab==='browse-panel'} files={files??{data:[],current_page:1,last_page:1,per_page:24,total:0,from:null,to:null}} stats={stats??{total_files:0,total_size:0,by_type:{video:0,image:0,audio:0,document:0}}} filters={filters} departments={departments} currentUser={currentUser} filterOwners={filterOwners} masterData={masterData} metadataSettings={metadataSettings} savedSearches={savedSearches} quickViewCounts={quickViewCounts} searchSettings={searchSettings} simulatedRole={simulatedRole} selectedFiles={selectedFiles} onFilterType={type=>go({type:type==='all'?undefined:type})} onFilterChange={next=>go(next,['files','filters','stats','filterOwners','quickViewCounts'])} onSort={sort=>router.get('/',{...filters,sort},{preserveState:true,preserveScroll:true,only:['files','filters']})} onSelectAll={selectAll} onToggleSelect={toggle} onToggleFavorite={toggleFavorite} onOpenPreview={openPreview} onPageChange={page=>router.get('/',{...filters,page},{preserveState:true,preserveScroll:true,only:['files','filters']})} onSaveSearch={saveSearch} onApplySavedSearch={applySavedSearch} onDeleteSavedSearch={deleteSavedSearch}/></Deferred></PanelErrorBoundary>
  {activeTab==='upload-panel'&&canUpload&&<PanelErrorBoundary panelName="Batch Upload" resetKey={activeTab} onReturn={()=>switchTab('browse-panel')}><UploadPanel active categories={categories} simulatedRole={simulatedRole} masterData={masterData} metadataSettings={metadataSettings} uploadSettings={uploadSettings} onSuccess={m=>toast(m,'success')} onError={m=>toast(m,'error')}/></PanelErrorBoundary>}
  {activeTab==='access-panel'&&canViewAccess&&<PanelErrorBoundary panelName="Access Requests" resetKey={activeTab} onReturn={()=>switchTab('browse-panel')}><AccessPanel active users={users} departments={departments} organizationUnits={organizationUnits} permissionSets={permissionSets} approvalDelegations={approvalDelegations} categories={categories} masterData={masterData} accessMaturitySettings={accessMaturitySettings} accessRequests={accessRequests} simulatedRole={simulatedRole} currentUser={currentUser} onSuccess={m=>toast(m,'success')} onError={m=>toast(m,'error')}/></PanelErrorBoundary>}
  {activeTab==='notifications-panel'&&<PanelErrorBoundary panelName="Notifications" resetKey={activeTab} onReturn={()=>switchTab('browse-panel')}><NotificationsPanel active notifications={notifications} unread={unreadNotifications} preferences={notificationPreferences} onSuccess={m=>toast(m,'success')} onError={m=>toast(m,'error')}/></PanelErrorBoundary>}
  {activeTab==='reports-panel'&&canViewReports&&<PanelErrorBoundary panelName="Dashboards & Reports" resetKey={activeTab} onReturn={()=>switchTab('browse-panel')}><ReportsPanel active role={currentUser.role} onError={m=>toast(m,'error')}/></PanelErrorBoundary>}
  {activeTab==='integrations-panel'&&canViewIntegrations&&<PanelErrorBoundary panelName="Integrations & Health" resetKey={activeTab} onReturn={()=>switchTab('browse-panel')}><IntegrationsPanel active role={currentUser.role} summary={integrationHealthSummary} categories={categories} departments={departments} masterData={masterData} metadataSettings={metadataSettings} onSuccess={m=>toast(m,'success')} onError={m=>toast(m,'error')}/></PanelErrorBoundary>}
  {activeTab==='guide-panel'&&canViewUserGuide&&<PanelErrorBoundary panelName="User Guide Manual" resetKey={activeTab} onReturn={()=>switchTab('browse-panel')}><UserGuidePanel active access={userGuideAccess} onError={m=>toast(m,'error')}/></PanelErrorBoundary>}
  {activeTab==='settings-panel'&&canViewSettings&&<PanelErrorBoundary panelName="Settings" resetKey={activeTab} onReturn={()=>switchTab('browse-panel')}><SettingsPanel active categories={categories} departments={departments} users={users} currentUser={currentUser} organizationUnits={organizationUnits} portalRoles={portalRoles} userGroups={userGroups} networkPolicySummary={networkPolicySummary} appVersion={appVersion} stats={stats} simulatedRole={simulatedRole} canConfigCategories={canConfigCategories} canManageDepartments={canManageDepartments} fontFamilies={fontFamilies} appearanceSettings={appearanceSettings} searchSettings={searchSettings} masterData={masterData} metadataSettings={metadataSettings} notificationSettings={notificationSettings} notificationEscalation={notificationEscalation} uploadSettings={uploadSettings} securityAuthSettings={securityAuthSettings} accessMaturitySettings={accessMaturitySettings} backupSettings={backupSettings} backupRuns={backupRuns} restoreVerifications={restoreVerifications} backupStatus={backupStatus} readinessData={readinessData} featureCompletionSettings={featureCompletionSettings||{}} onAddSubcategory={id=>openCategory(id)} onAddMainCategory={()=>openCategory(null)} onSuccess={m=>toast(m,'success')} onError={m=>toast(m,'error')}/></PanelErrorBoundary>}
 </AppLayout>
 {previewFile&&<Suspense fallback={null}><PreviewModal file={previewFile} categories={categories} canDelete={canDelete} uploadSettings={uploadSettings} sourceConnections={sourceConnections} lifecycleSettings={(featureCompletionSettings?.lifecycle||{}) as {transitions?:Record<string,string[]>}} onClose={()=>setPreviewFile(null)} onDownload={()=>handleDownload(previewFile.id)} onDelete={()=>handleDelete(previewFile.id)} onRequestAccess={requestAccess} onUpdatePolicy={updatePolicy} onLifecycleChanged={()=>{setPreviewFile(null);router.reload({only:['files','stats']})}}/></Suspense>}
 {showCategoryModal&&<Suspense fallback={null}><CategoryModal parentId={categoryParent} categories={categories} onClose={()=>setShowCategoryModal(false)} onSuccess={m=>{setShowCategoryModal(false);toast(m,'success')}} onError={m=>toast(m,'error')}/></Suspense>}
 {showBulkEdit&&<Suspense fallback={null}><BulkEditModal ids={Array.from(selectedFiles)} categories={categories} departments={departments} masterData={masterData} role={simulatedRole} onClose={()=>setShowBulkEdit(false)} onSuccess={m=>{toast(m,'success');setSelectedFiles(new Set());router.reload({only:['files','stats','categories','filterOwners']})}} onError={m=>toast(m,'error')}/></Suspense>}
 {selectedFiles.size>0&&<FloatingActionBar selectedCount={selectedFiles.size} canDelete={canDelete} canBulkEdit={canBulkEdit} onBulkEdit={()=>setShowBulkEdit(true)} onDownload={handleDownloadZip} onDelete={()=>handleDelete()} onClear={()=>setSelectedFiles(new Set())}/>}<Toast toasts={toasts} onRemove={id=>setToasts(x=>x.filter(t=>t.id!==id))}/></>;
}
