import { FormEvent, useEffect, useState } from 'react';
import { useForm, Link, router } from '@inertiajs/react';
import { ArrowLeft, User, Lock, LogOut, CheckCircle, Monitor, ShieldAlert, ShieldCheck, KeyRound, Languages, Palette, Globe2, Building2, Users } from 'lucide-react';
import type { BrandingSettings, UiTheme, User as UserType } from '../types';
import { usePortalBranding } from '../branding';

interface Props {
    user: UserType;
    branding?: BrandingSettings;
    networkPolicy?: { enabled:boolean; current_access_source:string };
    flash?: { success?: string; warning?: string };
}
interface BrowserSession { id:string; current:boolean; ip_address?:string|null; last_activity?:string|null; user_agent?:string|null; }
interface TwoFactorSetup { secret:string; otpauth_uri:string; }
const themeChoices:{key:UiTheme;label:string;help:string;colors:string[]}[]=[
    {key:'smvs',label:'SMVS Teal',help:'Portal default balanced teal theme.',colors:['#2a9d8f','#264653','#e9c46a']},
    {key:'slack',label:'Slack Inspired',help:'Purple with aqua/green communication accents.',colors:['#611f69','#36c5f0','#2eb67d']},
    {key:'google',label:'Google Inspired',help:'Blue with familiar red/yellow/green accents.',colors:['#1a73e8','#ea4335','#34a853']},
];

export default function Profile({ user, flash, networkPolicy={enabled:false,current_access_source:'unknown'} }: Props) {
    const { branding } = usePortalBranding();
    const [sessions,setSessions]=useState<BrowserSession[]>([]),[sessionMsg,setSessionMsg]=useState('');
    const [twoFactorEnabled,setTwoFactorEnabled]=useState(Boolean(user.two_factor_confirmed_at));
    const [twoFactorSetup,setTwoFactorSetup]=useState<TwoFactorSetup|null>(null),[twoFactorCode,setTwoFactorCode]=useState(''),[twoFactorPassword,setTwoFactorPassword]=useState(''),[twoFactorBusy,setTwoFactorBusy]=useState(false),[twoFactorMessage,setTwoFactorMessage]=useState(''),[recoveryCodes,setRecoveryCodes]=useState<string[]>([]);
    const csrf=()=>document.querySelector('meta[name="csrf-token"]')?.getAttribute('content')||'';
    const jsonError=async(response:Response,fallback:string)=>{let data:any={};try{data=await response.json()}catch{return fallback}if(response.status===423&&data.redirect){router.visit(data.redirect);return data.message||fallback}return data.message||Object.values(data.errors||{}).flat().join('; ')||fallback};
    const loadSessions=async()=>{try{const r=await fetch('/sessions',{headers:{Accept:'application/json'}});const d=await r.json();if(r.ok)setSessions(d.sessions||[])}catch{setSessionMsg('Could not load active sessions.')}};
    useEffect(()=>{void loadSessions()},[]);
    useEffect(()=>{document.documentElement.setAttribute('data-color-theme',user.ui_theme||'smvs')},[user.ui_theme]);

    const logoutSession=async(id:string)=>{const r=await fetch(`/sessions/${id}`,{method:'DELETE',headers:{'X-CSRF-TOKEN':csrf(),Accept:'application/json'}});const d=await r.json();setSessionMsg(d.message||'Session updated.');void loadSessions()};
    const logoutOthers=async()=>{const r=await fetch('/sessions/others',{method:'DELETE',headers:{'X-CSRF-TOKEN':csrf(),Accept:'application/json'}});const d=await r.json();setSessionMsg(d.message||'Other sessions logged out.');void loadSessions()};

    const infoForm=useForm({name:user.name,email:user.email,phone:user.phone??'',preferred_language:user.preferred_language??branding.default_language??'en',ui_theme:(user.ui_theme??'smvs') as UiTheme});
    const passwordForm=useForm({current_password:'',password:'',password_confirmation:''});
    const submitInfo=(e:FormEvent)=>{e.preventDefault();infoForm.patch('/profile',{preserveScroll:true,onSuccess:()=>document.documentElement.setAttribute('data-color-theme',infoForm.data.ui_theme)})};
    const chooseTheme=(theme:UiTheme)=>{infoForm.setData('ui_theme',theme);document.documentElement.setAttribute('data-color-theme',theme)};
    const submitPassword=(e:FormEvent)=>{e.preventDefault();passwordForm.patch('/profile/password',{preserveScroll:true,onSuccess:()=>passwordForm.reset()})};

    const startTwoFactor=async()=>{setTwoFactorBusy(true);setTwoFactorMessage('');setRecoveryCodes([]);try{const r=await fetch('/profile/two-factor/setup',{method:'POST',headers:{'X-CSRF-TOKEN':csrf(),Accept:'application/json'}});if(!r.ok)throw new Error(await jsonError(r,'Could not start two-factor setup.'));setTwoFactorSetup(await r.json());setTwoFactorMessage('Add this account to your authenticator app, then enter the current 6-digit code.')}catch(e){setTwoFactorMessage(e instanceof Error?e.message:'Could not start two-factor setup.')}finally{setTwoFactorBusy(false)}};
    const confirmTwoFactor=async()=>{if(!twoFactorCode.trim())return;setTwoFactorBusy(true);setTwoFactorMessage('');try{const r=await fetch('/profile/two-factor/confirm',{method:'POST',headers:{'X-CSRF-TOKEN':csrf(),'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({code:twoFactorCode.trim()})});if(!r.ok)throw new Error(await jsonError(r,'Could not confirm two-factor authentication.'));const d=await r.json();setRecoveryCodes(d.recovery_codes||[]);setTwoFactorEnabled(true);setTwoFactorSetup(null);setTwoFactorCode('');setTwoFactorMessage('Two-factor authentication is enabled. Save the recovery codes below now; they are shown only once.')}catch(e){setTwoFactorMessage(e instanceof Error?e.message:'Could not confirm two-factor authentication.')}finally{setTwoFactorBusy(false)}};
    const disableTwoFactor=async()=>{if(!twoFactorPassword){setTwoFactorMessage('Enter your current password to disable two-factor authentication.');return}if(!confirm('Disable two-factor authentication for this account?'))return;setTwoFactorBusy(true);setTwoFactorMessage('');try{const r=await fetch('/profile/two-factor',{method:'DELETE',headers:{'X-CSRF-TOKEN':csrf(),'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({password:twoFactorPassword})});if(!r.ok)throw new Error(await jsonError(r,'Could not disable two-factor authentication.'));const d=await r.json();setTwoFactorEnabled(false);setTwoFactorPassword('');setRecoveryCodes([]);setTwoFactorSetup(null);setTwoFactorMessage(d.message||'Two-factor authentication disabled.')}catch(e){setTwoFactorMessage(e instanceof Error?e.message:'Could not disable two-factor authentication.')}finally{setTwoFactorBusy(false)}};

    const initials=user.name.split(' ').map(n=>n[0]).join('').slice(0,2).toUpperCase();
    const externalActive=Boolean(user.external_access_allowed)&&(!user.external_access_starts_at||new Date(user.external_access_starts_at)<=new Date())&&(!user.external_access_expires_at||new Date(user.external_access_expires_at)>new Date());
    const roleName=user.portal_role?.name||user.role.replaceAll('-',' ');

    return <div className="profile-page">
      <header className="profile-topbar"><Link href="/" className="profile-back-btn"><ArrowLeft size={16}/><span>Back to Dashboard</span></Link><div className="profile-topbar-brand"><img src={branding.logo_url} alt={branding.portal_name} onError={e=>{if(!e.currentTarget.src.endsWith('/logo.svg'))e.currentTarget.src='/logo.svg';else e.currentTarget.style.display='none'}}/><span>{branding.portal_name}</span></div><button className="logout-btn" onClick={()=>router.post('/logout')}><LogOut size={16}/><span>Logout</span></button></header>
      <div className="profile-body">
        <div className="profile-hero"><div className="profile-avatar-lg">{initials}</div><div><h1 className="profile-hero-name">{user.name}</h1><div style={{display:'flex',gap:7,flexWrap:'wrap',marginTop:5}}><span className="profile-hero-role">{roleName}</span>{user.department?.name&&<span className="profile-hero-role"><Building2 size={11}/>{user.department.name}</span>}{(user.groups||[]).map(g=><span className="profile-hero-role" key={g.id}><Users size={11}/>{g.name}</span>)}</div></div></div>
        {flash?.warning&&<div className="profile-error-banner" style={{marginBottom:16}}><ShieldAlert size={16}/><span>{flash.warning}</span></div>}{flash?.success&&<div className="profile-flash"><CheckCircle size={16}/><span>{flash.success}</span></div>}

        <div className="profile-grid">
          <div className="profile-card"><h2 className="profile-card-title"><User size={18}/>Personal Information</h2><form onSubmit={submitInfo} className="profile-form">
            <div className="profile-field"><label htmlFor="name">Full name</label><input id="name" value={infoForm.data.name} onChange={e=>infoForm.setData('name',e.target.value)}/>{infoForm.errors.name&&<span className="profile-field-error">{infoForm.errors.name}</span>}</div>
            <div className="profile-field"><label htmlFor="email">Email address</label><input id="email" type="email" value={infoForm.data.email} onChange={e=>infoForm.setData('email',e.target.value)}/>{infoForm.errors.email&&<span className="profile-field-error">{infoForm.errors.email}</span>}</div>
            <div className="profile-field"><label htmlFor="phone">Phone <span className="profile-optional">(optional)</span></label><input id="phone" type="tel" value={infoForm.data.phone} onChange={e=>infoForm.setData('phone',e.target.value)}/></div>
            <div className="profile-field"><label htmlFor="preferred_language"><Languages size={14}/> Interface language</label><select id="preferred_language" value={infoForm.data.preferred_language} onChange={e=>infoForm.setData('preferred_language',e.target.value as 'en'|'gu')}><option value="en">English</option><option value="gu">ગુજરાતી</option></select></div>
            <div className="profile-field profile-field-static"><label>Assigned role</label><span className="profile-role-badge">{roleName}</span></div><button type="submit" className="profile-save-btn" disabled={infoForm.processing}>{infoForm.processing?'Saving…':'Save Profile'}</button>
          </form></div>

          <div className="profile-card"><h2 className="profile-card-title"><Globe2 size={18}/>Network Access</h2><div className="profile-security-summary"><div><span>Network policy</span><b>{networkPolicy.enabled?'Internal / VPN Only':'Restriction not enabled'}</b></div><div><span>Current sign-in source</span><b style={{textTransform:'capitalize'}}>{networkPolicy.current_access_source.replaceAll('_',' ')}</b></div><div><span>External Internet exception</span><b>{externalActive?'Allowed now':user.external_access_allowed?'Scheduled / expired':'Blocked'}</b></div>{user.external_access_starts_at&&<div><span>External start</span><b>{new Date(user.external_access_starts_at).toLocaleString()}</b></div>}{user.external_access_expires_at&&<div><span>External expiry</span><b>{new Date(user.external_access_expires_at).toLocaleString()}</b></div>}{user.external_access_reason&&<div><span>Reason</span><b>{user.external_access_reason}</b></div>}{user.external_access_approver?.name&&<div><span>Approved by</span><b>{user.external_access_approver.name}</b></div>}</div><div className="admin-guide" style={{marginTop:12}}>External Internet permission is managed by authorized administrators. The same portal URL is used internally, over VPN and externally; the server decides access after secure sign-in.</div></div>

          <div className="profile-card" style={{gridColumn:'1 / -1'}}><h2 className="profile-card-title"><Palette size={18}/>Color Theme</h2><p className="setting-help">Choose a color combination for your own account. The selection is saved to your profile and follows you when you sign in on another device.</p><div className="theme-choice-grid" style={{marginTop:12}}>{themeChoices.map(t=><button type="button" className={`theme-choice${infoForm.data.ui_theme===t.key?' active':''}`} onClick={()=>chooseTheme(t.key)} key={t.key}><b>{t.label}</b><div className="setting-help">{t.help}</div><div className="theme-swatch">{t.colors.map(c=><i key={c} style={{background:c}}/>)}</div></button>)}</div><button className="btn btn-primary" style={{marginTop:12}} onClick={()=>infoForm.patch('/profile',{preserveScroll:true,onSuccess:()=>document.documentElement.setAttribute('data-color-theme',infoForm.data.ui_theme)})}>Save Theme as My Default</button></div>

          <div className="profile-card"><h2 className="profile-card-title"><Lock size={18}/>Change Password</h2><form onSubmit={submitPassword} className="profile-form"><div className="profile-field"><label>Current password</label><input type="password" value={passwordForm.data.current_password} onChange={e=>passwordForm.setData('current_password',e.target.value)} autoComplete="current-password"/>{passwordForm.errors.current_password&&<span className="profile-field-error">{passwordForm.errors.current_password}</span>}</div><div className="profile-field"><label>New password</label><input type="password" value={passwordForm.data.password} onChange={e=>passwordForm.setData('password',e.target.value)} autoComplete="new-password"/>{passwordForm.errors.password&&<span className="profile-field-error">{passwordForm.errors.password}</span>}</div><div className="profile-field"><label>Confirm new password</label><input type="password" value={passwordForm.data.password_confirmation} onChange={e=>passwordForm.setData('password_confirmation',e.target.value)} autoComplete="new-password"/></div><button type="submit" className="profile-save-btn" disabled={passwordForm.processing}>{passwordForm.processing?'Updating…':'Change Password'}</button></form></div>

          <div className="profile-card"><h2 className="profile-card-title">{twoFactorEnabled?<ShieldCheck size={18}/>:<KeyRound size={18}/>}Two-Factor Authentication</h2><p className="setting-help">Protect this account with a TOTP authenticator. Recovery codes can be used once if the authenticator is unavailable.</p>{twoFactorMessage&&<div className={twoFactorEnabled?'profile-flash':'profile-error-banner'} style={{marginTop:10,marginBottom:10}}>{twoFactorMessage}</div>}{!twoFactorEnabled&&!twoFactorSetup&&<button className="btn btn-primary" disabled={twoFactorBusy} onClick={startTwoFactor}>{twoFactorBusy?'Preparing…':'Set up authenticator'}</button>}{!twoFactorEnabled&&twoFactorSetup&&<div style={{display:'grid',gap:10}}><div className="profile-field"><label>Authenticator secret</label><input readOnly value={twoFactorSetup.secret} onFocus={e=>e.currentTarget.select()}/></div><div className="profile-field"><label>Authenticator URI</label><input readOnly value={twoFactorSetup.otpauth_uri} onFocus={e=>e.currentTarget.select()}/></div><div className="profile-field"><label>Current 6-digit code</label><input inputMode="numeric" autoComplete="one-time-code" value={twoFactorCode} onChange={e=>setTwoFactorCode(e.target.value)}/></div><div style={{display:'flex',gap:8}}><button className="btn btn-primary" onClick={confirmTwoFactor}>Confirm & Enable</button><button className="btn btn-secondary" onClick={()=>setTwoFactorSetup(null)}>Cancel</button></div></div>}{twoFactorEnabled&&<div style={{display:'grid',gap:10}}><div className="profile-field"><label>Current password to disable</label><input type="password" value={twoFactorPassword} onChange={e=>setTwoFactorPassword(e.target.value)}/></div><button className="btn btn-secondary" onClick={disableTwoFactor}>Disable Two-Factor Authentication</button></div>}{recoveryCodes.length>0&&<div style={{marginTop:12,border:'1px solid var(--border-color)',borderRadius:8,padding:12}}><strong>Recovery codes — store securely now</strong><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:6,marginTop:8,fontFamily:'monospace'}}>{recoveryCodes.map(c=><code key={c}>{c}</code>)}</div></div>}</div>

          <div className="profile-card" style={{gridColumn:'1 / -1'}}><h2 className="profile-card-title"><Monitor size={18}/>Active Sessions</h2><p className="setting-help">Review browser/device sessions and revoke any session you no longer recognize.</p>{sessionMsg&&<div className="profile-flash" style={{marginTop:10}}>{sessionMsg}</div>}<div style={{display:'grid',gap:8,marginTop:12}}>{sessions.map(s=><div key={s.id} className="setting-row"><div><b>{s.current?'Current session':'Other session'}</b><div className="setting-help">{s.ip_address||'Unknown IP'} · {s.last_activity?new Date(s.last_activity).toLocaleString():'-'}</div><div style={{fontSize:10,color:'var(--text-muted)',maxWidth:760,overflow:'hidden',textOverflow:'ellipsis'}}>{s.user_agent||'Unknown browser'}</div></div>{!s.current&&<button className="btn btn-secondary" onClick={()=>logoutSession(s.id)}>Logout</button>}</div>)}</div><button className="btn btn-secondary" style={{marginTop:10}} onClick={logoutOthers}>Logout All Other Sessions</button></div>
        </div>
      </div>
    </div>
}
