import { useMemo, useState } from 'react';
import { router } from '@inertiajs/react';
import { AlertTriangle, CheckCircle2, DatabaseBackup, Download, HardDrive, PlayCircle, RefreshCw, ShieldCheck } from 'lucide-react';
import type { BackupRunRow, BackupSettings, BackupStatusSummary, RestoreVerificationRow } from '../../types';

interface Props {
 settings:BackupSettings; runs:BackupRunRow[]; verifications:RestoreVerificationRow[]; status:BackupStatusSummary;
 onSuccess:(message:string)=>void; onError:(message:string)=>void;
}
const Toggle=({checked,onChange}:{checked:boolean;onChange:(v:boolean)=>void})=><label className="toggle-switch"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><span className="toggle-track"/></label>;
const fmtBytes=(n:number|null)=>{if(!n)return'—';const units=['B','KB','MB','GB','TB'];let v=n,i=0;while(v>=1024&&i<units.length-1){v/=1024;i++}return`${v.toFixed(i?1:0)} ${units[i]}`};
const fmtDate=(v:string|null)=>v?new Date(v).toLocaleString():'—';

export default function BackupSettingsPanel(p:Props){
 const [settings,setSettings]=useState<BackupSettings>({...p.settings});
 const [restoreBackupId,setRestoreBackupId]=useState<number>(p.runs.find(r=>r.status==='success')?.id||0);
 const [restoreStatus,setRestoreStatus]=useState<'passed'|'failed'>('passed');
 const [restoreDuration,setRestoreDuration]=useState(0); const [restoreEnv,setRestoreEnv]=useState('Staging restore test'); const [restoreNotes,setRestoreNotes]=useState('');
 const successful=useMemo(()=>p.runs.filter(r=>r.status==='success'),[p.runs]);
 const save=()=>router.patch('/settings/backups',settings as any,{preserveScroll:true,onSuccess:()=>p.onSuccess('Backup & DR settings saved.'),onError:e=>p.onError(String(Object.values(e)[0]||'Backup settings failed'))});
 const create=()=>router.post('/settings/backups/create',{}, {preserveScroll:true,onSuccess:()=>p.onSuccess('Manual encrypted backup created and integrity-verified.'),onError:e=>p.onError(String(Object.values(e)[0]||'Backup failed'))});
 const verify=(id:number)=>router.post(`/settings/backups/${id}/verify`,{}, {preserveScroll:true,onSuccess:()=>p.onSuccess('Backup integrity verification completed.'),onError:e=>p.onError(String(Object.values(e)[0]||'Verification failed'))});
 const prune=()=>router.post('/settings/backups/prune',{}, {preserveScroll:true,onSuccess:()=>p.onSuccess('Retention scan completed.'),onError:e=>p.onError(String(Object.values(e)[0]||'Retention scan failed'))});
 const recordRestore=()=>{if(!restoreBackupId)return p.onError('Select a successful backup.');router.post(`/settings/backups/${restoreBackupId}/restore-verification`,{status:restoreStatus,duration_minutes:restoreDuration,target_environment:restoreEnv,notes:restoreNotes},{preserveScroll:true,onSuccess:()=>p.onSuccess('Restore test verification recorded.'),onError:e=>p.onError(String(Object.values(e)[0]||'Could not record restore test'))})};
 const readiness=p.status.readiness;
 return <div style={{display:'grid',gap:18}}>
  <div className="admin-guide"><b>Backup boundary:</b> this application-native encrypted archive protects portal DB/metadata, System Settings/configuration and audit/security records. It deliberately does <b>not</b> embed NAS / Google Drive / YouTube source-content bytes. Those remain the responsibility of the source-system owner. The matching <b>APP_KEY must be held separately in secure DR custody</b>; it is never stored inside the backup.</div>
  <div className="settings-grid">
   <div className="settings-card"><h2 className="settings-card-title"><ShieldCheck size={18}/> DR Readiness</h2><div style={{fontSize:24,fontWeight:800,textTransform:'capitalize',color:readiness==='ready'?'var(--color-success)':readiness==='warning'?'var(--color-warning)':'var(--text-secondary)'}}>{readiness.replace('-',' ')}</div><div className="setting-help">Latest backup: {fmtDate(p.status.latest_backup_at)}{p.status.latest_backup_age_minutes!=null?` · ${p.status.latest_backup_age_minutes} min old`:''}</div><div className="setting-help">Last passed restore test: {fmtDate(p.status.last_restore_test_at)}{p.status.last_restore_duration_minutes!=null?` · ${p.status.last_restore_duration_minutes} min`:''}</div></div>
   <div className="settings-card"><h2 className="settings-card-title"><DatabaseBackup size={18}/> RPO / RTO</h2><div className="setting-help">RPO target: {p.status.rpo_target_minutes||'Policy Pending'}{p.status.rpo_target_minutes?` min · ${p.status.rpo_met===true?'MET':p.status.rpo_met===false?'MISSED':'UNKNOWN'}`:''}</div><div className="setting-help">RTO target: {p.status.rto_target_minutes||'Policy Pending'}{p.status.rto_target_minutes?` min · ${p.status.rto_met===true?'MET':p.status.rto_met===false?'MISSED':'UNKNOWN'}`:''}</div><div className="setting-help">Retention: {p.status.retention_policy_pending?'Policy Pending':'Configured'}</div></div>
  </div>

  <div className="settings-card"><h2 className="settings-card-title"><HardDrive size={18}/> Destination & Scope</h2><div className="settings-grid"><div><label className="form-label">Backup Destination</label><select className="form-select" value={settings.destination_type} onChange={e=>setSettings({...settings,destination_type:e.target.value as 'local'|'filesystem'})}><option value="local">Protected Local Storage</option><option value="filesystem">External / NAS Filesystem Path</option></select></div><div><label className="form-label">Responsible Owner</label><input className="form-input" value={settings.responsible_owner} onChange={e=>setSettings({...settings,responsible_owner:e.target.value})} placeholder="IT / Infrastructure owner"/></div>{settings.destination_type==='filesystem'&&<div style={{gridColumn:'1/-1'}}><label className="form-label">Existing Writable Absolute Directory</label><input className="form-input" value={settings.filesystem_path} onChange={e=>setSettings({...settings,filesystem_path:e.target.value})} placeholder="/mnt/backup/karyalay-portal"/><div className="setting-help">Must exist, be writable by the application container and must not be inside the public web directory.</div></div>}</div><div style={{display:'grid',gap:8,marginTop:12}}>{[['backup_database','Portal DB / metadata'],['backup_configuration','System settings / roles / policies / integration config'],['backup_audit_security','Audit / security records']].map(([key,label])=><div className="setting-row" key={key}><div><div className="setting-title">{label}</div></div><Toggle checked={Boolean((settings as any)[key])} onChange={v=>setSettings({...settings,[key]:v})}/></div>)}</div></div>

  <div className="settings-card"><h2 className="settings-card-title"><RefreshCw size={18}/> Scheduled Backups</h2><div className="admin-guide">Schedules remain OFF by default until Management/IT approves them. The scheduler checks hourly and creates each enabled daily/weekly/monthly class at most once in its period.</div><div style={{display:'grid',gap:10,marginTop:12}}><div className="setting-row"><div><div className="setting-title">Daily</div><div className="setting-help">Hour (0–23): {settings.daily_hour}:00</div></div><div style={{display:'flex',gap:10,alignItems:'center'}}><input className="form-input" style={{width:90}} type="number" min={0} max={23} value={settings.daily_hour} onChange={e=>setSettings({...settings,daily_hour:Number(e.target.value)})}/><Toggle checked={settings.daily_enabled} onChange={v=>setSettings({...settings,daily_enabled:v})}/></div></div><div className="setting-row"><div><div className="setting-title">Weekly</div><div className="setting-help">Day 0=Sunday … 6=Saturday</div></div><div style={{display:'flex',gap:8}}><input className="form-input" style={{width:90}} type="number" min={0} max={6} value={settings.weekly_day} onChange={e=>setSettings({...settings,weekly_day:Number(e.target.value)})}/><input className="form-input" style={{width:90}} type="number" min={0} max={23} value={settings.weekly_hour} onChange={e=>setSettings({...settings,weekly_hour:Number(e.target.value)})}/><Toggle checked={settings.weekly_enabled} onChange={v=>setSettings({...settings,weekly_enabled:v})}/></div></div><div className="setting-row"><div><div className="setting-title">Monthly</div><div className="setting-help">Day 1–28; configured hour uses server timezone.</div></div><div style={{display:'flex',gap:8}}><input className="form-input" style={{width:90}} type="number" min={1} max={28} value={settings.monthly_day} onChange={e=>setSettings({...settings,monthly_day:Number(e.target.value)})}/><input className="form-input" style={{width:90}} type="number" min={0} max={23} value={settings.monthly_hour} onChange={e=>setSettings({...settings,monthly_hour:Number(e.target.value)})}/><Toggle checked={settings.monthly_enabled} onChange={v=>setSettings({...settings,monthly_enabled:v})}/></div></div></div></div>

  <div className="settings-card"><h2 className="settings-card-title"><AlertTriangle size={18}/> Retention & DR Targets</h2><div className="admin-guide"><b>0 means Policy Pending / no automatic enforcement.</b> Set values only after Management/IT approval. Manual backups are never auto-pruned.</div><div className="settings-grid" style={{marginTop:12}}><div><label className="form-label">Daily Retention (days)</label><input className="form-input" type="number" min={0} value={settings.daily_retention_days} onChange={e=>setSettings({...settings,daily_retention_days:Number(e.target.value)})}/></div><div><label className="form-label">Weekly Retention (days)</label><input className="form-input" type="number" min={0} value={settings.weekly_retention_days} onChange={e=>setSettings({...settings,weekly_retention_days:Number(e.target.value)})}/></div><div><label className="form-label">Monthly Retention (days)</label><input className="form-input" type="number" min={0} value={settings.monthly_retention_days} onChange={e=>setSettings({...settings,monthly_retention_days:Number(e.target.value)})}/></div><div><label className="form-label">RPO Target (minutes)</label><input className="form-input" type="number" min={0} value={settings.rpo_minutes} onChange={e=>setSettings({...settings,rpo_minutes:Number(e.target.value)})}/></div><div><label className="form-label">RTO Target (minutes)</label><input className="form-input" type="number" min={0} value={settings.rto_minutes} onChange={e=>setSettings({...settings,rto_minutes:Number(e.target.value)})}/></div></div><label className="form-label" style={{marginTop:12}}>External Source Backup Responsibility</label><textarea className="form-input" rows={3} value={settings.external_source_responsibility} onChange={e=>setSettings({...settings,external_source_responsibility:e.target.value})}/><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:12}}><button className="btn btn-primary" onClick={save}>Save Backup / DR Settings</button><button className="btn btn-secondary" onClick={create}><PlayCircle size={14}/> Create Backup Now</button><button className="btn btn-secondary" onClick={prune}><RefreshCw size={14}/> Run Retention Scan</button></div></div>

  <div className="settings-card"><h2 className="settings-card-title"><CheckCircle2 size={18}/> Backup History</h2>{p.runs.length===0?<div className="admin-guide">No backup run has been recorded yet.</div>:<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:11}}><thead><tr><th style={{textAlign:'left'}}>ID / Class</th><th style={{textAlign:'left'}}>Status</th><th style={{textAlign:'left'}}>Completed</th><th style={{textAlign:'right'}}>Size</th><th style={{textAlign:'left'}}>Integrity</th><th>Actions</th></tr></thead><tbody>{p.runs.map(r=><tr key={r.id}><td style={{padding:'8px 4px'}}>#{r.id} · {r.trigger}/{r.retention_class}</td><td>{r.status}{r.error?<div style={{color:'var(--color-danger)',maxWidth:260}}>{r.error}</div>:null}</td><td>{fmtDate(r.completed_at)}</td><td style={{textAlign:'right'}}>{fmtBytes(r.size_bytes)}</td><td>{r.verified_at?`Verified ${fmtDate(r.verified_at)}`:'Not verified'}</td><td style={{textAlign:'center',whiteSpace:'nowrap'}}>{r.status==='success'&&<><button className="btn btn-secondary" style={{padding:'5px 7px',fontSize:10}} onClick={()=>verify(r.id)}>Verify</button> <a className="btn btn-secondary" style={{padding:'5px 7px',fontSize:10}} href={`/settings/backups/${r.id}/download`}><Download size={12}/> Download</a></>}</td></tr>)}</tbody></table></div>}</div>

  <div className="settings-card"><h2 className="settings-card-title"><DatabaseBackup size={18}/> Restore Procedure & Verification Record</h2><div className="admin-guide"><b>Safety rule:</b> destructive database restore is intentionally console-only and only supports a <b>fresh migrated target database</b>. In production, put Laravel into maintenance mode first. Use the same APP_KEY as the source backup. Example: <code>php artisan backup:restore-file &quot;/secure/path/file.kpbackup&quot; --confirm=RESTORE-EMPTY-DATABASE --force-production</code></div><div className="settings-grid" style={{marginTop:12}}><div><label className="form-label">Backup used for restore test</label><select className="form-select" value={restoreBackupId||''} onChange={e=>setRestoreBackupId(Number(e.target.value))}><option value="">-- Select successful backup --</option>{successful.map(r=><option key={r.id} value={r.id}>#{r.id} · {r.filename}</option>)}</select></div><div><label className="form-label">Result</label><select className="form-select" value={restoreStatus} onChange={e=>setRestoreStatus(e.target.value as 'passed'|'failed')}><option value="passed">Passed</option><option value="failed">Failed</option></select></div><div><label className="form-label">Restore duration (minutes)</label><input className="form-input" type="number" min={0} value={restoreDuration} onChange={e=>setRestoreDuration(Number(e.target.value))}/></div><div><label className="form-label">Target environment</label><input className="form-input" value={restoreEnv} onChange={e=>setRestoreEnv(e.target.value)}/></div></div><label className="form-label" style={{marginTop:10}}>Verification notes / evidence reference</label><textarea className="form-input" rows={3} value={restoreNotes} onChange={e=>setRestoreNotes(e.target.value)} placeholder="Example: Staging DB restored, user count/file metadata count checked, login smoke test passed."/><button className="btn btn-primary" style={{marginTop:10}} onClick={recordRestore}>Record Restore Verification</button>{p.verifications.length>0&&<div style={{marginTop:14,display:'grid',gap:7}}>{p.verifications.slice(0,12).map(v=><div key={v.id} className="setting-row"><div><div className="setting-title">{v.verification_type} · {v.status}</div><div className="setting-help">Backup #{v.backup_run_id||'—'} · {fmtDate(v.verified_at)} · {v.verified_by||'System'}{v.duration_minutes!=null?` · ${v.duration_minutes} min`:''}{v.target_environment?` · ${v.target_environment}`:''}</div>{v.notes&&<div className="setting-help">{v.notes}</div>}</div></div>)}</div>}</div>
 </div>;
}
