import { useMemo, useState } from 'react';
import { router } from '@inertiajs/react';

type SettingsMap=Record<string,Record<string,unknown>>;
const sections:[string,string][]=[['maintenance','Maintenance Mode'],['branding','Branding & Language'],['network','Network / VPN Policy'],['two_factor','Two-Factor Authentication'],['watermark','Watermark Policy'],['lifecycle','Lifecycle Workflow'],['type_required','Type-specific Metadata'],['audit_retention','Audit Retention'],['recycle_retention','Recycle Bin Retention'],['storage_quotas','Department Storage Quotas']];
export default function FeatureCompletionPanel({settings,onSuccess,onError}:{settings:SettingsMap;onSuccess:(m:string)=>void;onError:(m:string)=>void}){
 const initial=useMemo(()=>Object.fromEntries(sections.map(([k])=>[k,JSON.stringify(settings[k]||{},null,2)])),[settings]);
 const [text,setText]=useState<Record<string,string>>(initial); const [logo,setLogo]=useState<File|null>(null);
 const save=(section:string)=>{try{const parsed=JSON.parse(text[section]||'{}');router.patch('/settings/feature-completion',{section,settings:parsed},{preserveScroll:true,onSuccess:()=>onSuccess(`${section} settings saved.`),onError:e=>onError(String(Object.values(e)[0]||'Save failed'))})}catch{onError('Settings JSON is invalid.')}};
 const uploadLogo=()=>{if(!logo)return onError('Choose a PNG/JPEG/WEBP logo first.');router.post('/settings/branding/logo',{logo},{forceFormData:true,preserveScroll:true,onSuccess:()=>onSuccess('Portal logo updated.'),onError:e=>onError(String(Object.values(e)[0]||'Logo upload failed'))})};
 return <div style={{display:'grid',gap:16}}><div className="admin-guide"><b>v13.00 Completion Controls:</b> These settings are stored centrally and audited. Retention/quota values of 0 mean policy pending/unlimited as documented. Network changes are rejected if they would immediately lock out the current Super Admin.</div>{sections.map(([key,label])=><div className="settings-card" key={key}><h2 className="settings-card-title">{label}</h2><textarea className="form-input" rows={Math.min(16,Math.max(5,(text[key]||'').split('\n').length+1))} value={text[key]||''} onChange={e=>setText({...text,[key]:e.target.value})} spellCheck={false}/><button className="btn btn-primary" style={{marginTop:10}} onClick={()=>save(key)}>Save {label}</button>{key==='branding'&&<div style={{marginTop:12,display:'flex',gap:8,flexWrap:'wrap'}}><input type="file" accept=".png,.jpg,.jpeg,.webp" onChange={e=>setLogo(e.target.files?.[0]||null)}/><button className="btn btn-secondary" onClick={uploadLogo}>Upload Logo</button><button className="btn btn-secondary" onClick={()=>router.delete('/settings/branding/logo',{preserveScroll:true,onSuccess:()=>onSuccess('Logo reset.')})}>Reset Default Logo</button></div>}</div>)}</div>
}
