import { useEffect, useMemo, useState } from 'react';
import { router } from '@inertiajs/react';
import { Building2, Globe2, Image, Languages, LockKeyhole, Palette, Recycle, Save, ShieldCheck, ShieldOff, Wrench } from 'lucide-react';
import type { Department } from '../../types';

type SettingsMap=Record<string,Record<string,any>>;
const Toggle=({checked,onChange}:{checked:boolean;onChange:(v:boolean)=>void})=><label className="toggle-switch"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><span className="toggle-track"/></label>;
const lines=(v:unknown)=>Array.isArray(v)?v.join('\n'):'';
const toLines=(v:string)=>v.split(/[\n,]+/).map(x=>x.trim()).filter(Boolean);
const statuses=['draft','review','approved','published','archived'];
const requiredFields=['year','event_id','country_id','state_id','city_id','mandir_id','person_id','language_id','media_type_id','description'];
const fieldLabels:Record<string,string>={year:'Year',event_id:'Event / Prasang',country_id:'Country',state_id:'State',city_id:'City',mandir_id:'Mandir',person_id:'Guruji / Person',language_id:'Language',media_type_id:'Media Type',description:'Description'};

export default function FeatureCompletionPanel({settings,departments,onSuccess,onError}:{settings:SettingsMap;departments:Department[];onSuccess:(m:string)=>void;onError:(m:string)=>void}){
 const [maintenance,setMaintenance]=useState(()=>({enabled:Boolean(settings.maintenance?.enabled),message:String(settings.maintenance?.message||'The Karyalay Portal is temporarily under maintenance.'),allow_super_admin_bypass:settings.maintenance?.allow_super_admin_bypass!==false}));
 const [branding,setBranding]=useState(()=>({portal_name:String(settings.branding?.portal_name||'Karyalay Portal'),login_text:String(settings.branding?.login_text||'Secure office media and document portal'),default_language:String(settings.branding?.default_language||'en')}));
 const [network,setNetwork]=useState(()=>({enabled:Boolean(settings.network?.enabled),allowed_cidrs:lines(settings.network?.allowed_cidrs),trusted_vpn_proxies:lines(settings.network?.trusted_vpn_proxies),emergency_super_admin_email:String(settings.network?.emergency_super_admin_email||''),department_admin_can_manage_external_access:Boolean(settings.network?.department_admin_can_manage_external_access)}));
 const [twoFactor,setTwoFactor]=useState(()=>({enabled:settings.two_factor?.enabled!==false,required_super_admin:Boolean(settings.two_factor?.required_super_admin),issuer:String(settings.two_factor?.issuer||'Karyalay Portal')}));
 const [watermark,setWatermark]=useState(()=>({enabled:Boolean(settings.watermark?.enabled),text:String(settings.watermark?.text||'Karyalay Portal'),opacity:Number(settings.watermark?.opacity??18),protected_only:settings.watermark?.protected_only!==false}));
 const [lifecycle,setLifecycle]=useState<Record<string,string[]>>(()=>settings.lifecycle?.transitions||{draft:['review'],review:['draft','approved'],approved:['review','published'],published:['archived'],archived:['draft','published']});
 const [typeRequired,setTypeRequired]=useState<Record<string,string[]>>(()=>settings.type_required||{video:[],image:[],audio:[],document:[]});
 const [auditRetention,setAuditRetention]=useState(()=>({retention_days:Number(settings.audit_retention?.retention_days??0),archive_before_prune:settings.audit_retention?.archive_before_prune!==false,max_per_run:Number(settings.audit_retention?.max_per_run??1000)}));
 const [recycleRetention,setRecycleRetention]=useState(()=>({retention_days:Number(settings.recycle_retention?.retention_days??0),max_per_run:Number(settings.recycle_retention?.max_per_run??250)}));
 const [quota,setQuota]=useState(()=>({default_quota_gb:Number(settings.storage_quotas?.default_quota_gb??0),warning_percent:Number(settings.storage_quotas?.warning_percent??80),departments:{...(settings.storage_quotas?.departments||{})} as Record<string,number>}));
 const [logo,setLogo]=useState<File|null>(null);

 useEffect(()=>{setNetwork({enabled:Boolean(settings.network?.enabled),allowed_cidrs:lines(settings.network?.allowed_cidrs),trusted_vpn_proxies:lines(settings.network?.trusted_vpn_proxies),emergency_super_admin_email:String(settings.network?.emergency_super_admin_email||''),department_admin_can_manage_external_access:Boolean(settings.network?.department_admin_can_manage_external_access)})},[settings.network]);
 const save=(section:string,value:Record<string,unknown>)=>router.patch('/settings/feature-completion',{section,settings:value},{preserveScroll:true,onSuccess:()=>onSuccess(`${section.replaceAll('_',' ')} settings saved.`),onError:e=>onError(String(Object.values(e)[0]||'Save failed'))});
 const uploadLogo=()=>{if(!logo)return onError('Choose a PNG/JPEG/WEBP logo first.');router.post('/settings/branding/logo',{logo},{forceFormData:true,preserveScroll:true,onSuccess:()=>onSuccess('Portal logo updated.'),onError:e=>onError(String(Object.values(e)[0]||'Logo upload failed'))})};
 const toggleTransition=(from:string,to:string)=>setLifecycle(x=>{const current=x[from]||[];return{...x,[from]:current.includes(to)?current.filter(v=>v!==to):[...current,to]}});
 const toggleRequired=(type:string,field:string)=>setTypeRequired(x=>{const current=x[type]||[];return{...x,[type]:current.includes(field)?current.filter(v=>v!==field):[...current,field]}});

 return <div style={{display:'grid',gap:18}}>
  <div className="admin-guide"><b>Friendly Administration:</b> v15.00 removes raw JSON editing from these controls. Every policy now uses switches, fields and guided choices. Values of <b>0</b> for retention/quota remain Policy Pending / unlimited where documented.</div>

  <div className="settings-card"><h2 className="settings-card-title"><Wrench size={18}/> Maintenance Mode</h2><div className="setting-row"><div><div className="setting-title">Put portal in maintenance mode</div><div className="setting-help">Regular users receive the message below. Keep the Super Admin bypass on for safe recovery.</div></div><Toggle checked={maintenance.enabled} onChange={v=>setMaintenance({...maintenance,enabled:v})}/></div><div className="form-group"><label className="form-label">User message</label><input className="form-input" value={maintenance.message} onChange={e=>setMaintenance({...maintenance,message:e.target.value})}/></div><label className="check-row"><input type="checkbox" checked={maintenance.allow_super_admin_bypass} onChange={e=>setMaintenance({...maintenance,allow_super_admin_bypass:e.target.checked})}/>Allow Super Admin bypass</label><button className="btn btn-primary" onClick={()=>save('maintenance',maintenance)}><Save size={14}/> Save Maintenance Mode</button></div>

  <div className="settings-card"><h2 className="settings-card-title"><Palette size={18}/> Branding & Language</h2><div className="settings-grid"><div className="form-group"><label className="form-label">Portal name</label><input className="form-input" value={branding.portal_name} onChange={e=>setBranding({...branding,portal_name:e.target.value})}/></div><div className="form-group"><label className="form-label">Default language</label><select className="form-select" value={branding.default_language} onChange={e=>setBranding({...branding,default_language:e.target.value})}><option value="en">English</option><option value="gu">ગુજરાતી</option></select></div></div><div className="form-group"><label className="form-label">Login screen text</label><input className="form-input" value={branding.login_text} onChange={e=>setBranding({...branding,login_text:e.target.value})}/></div><button className="btn btn-primary" onClick={()=>save('branding',branding)}>Save Branding</button><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:10}}><input type="file" accept=".png,.jpg,.jpeg,.webp" onChange={e=>setLogo(e.target.files?.[0]||null)}/><button className="btn btn-secondary" onClick={uploadLogo}>Upload Logo</button><button className="btn btn-secondary" onClick={()=>router.delete('/settings/branding/logo',{preserveScroll:true,onSuccess:()=>onSuccess('Logo reset.')})}>Reset Default Logo</button></div></div>

  <div className="settings-card" style={{borderColor:'var(--color-primary)'}}><h2 className="settings-card-title"><Globe2 size={18}/> Network / VPN / External Internet</h2><div className="admin-guide"><b>Default policy:</b> Internal / VPN Only. When enabled, users outside the Internal/VPN ranges are blocked unless their individual user record has an active External Internet Access exception.</div><div className="setting-row"><div><div className="setting-title">Enforce Internal / VPN Only</div><div className="setting-help">Configure the ranges below before enabling. Current Super Admin lockout protection remains enforced by the server.</div></div><Toggle checked={network.enabled} onChange={v=>setNetwork({...network,enabled:v})}/></div><div className="settings-grid"><div className="form-group"><label className="form-label">Internal office IP/CIDR ranges</label><textarea className="form-input" rows={5} value={network.allowed_cidrs} onChange={e=>setNetwork({...network,allowed_cidrs:e.target.value})} placeholder={'192.168.1.0/24\n10.20.0.0/16'}/><div className="setting-help">One IP or CIDR per line.</div></div><div className="form-group"><label className="form-label">Approved VPN gateway/client CIDR ranges</label><textarea className="form-input" rows={5} value={network.trusted_vpn_proxies} onChange={e=>setNetwork({...network,trusted_vpn_proxies:e.target.value})} placeholder={'10.99.0.0/16\n203.0.113.10'}/><div className="setting-help">Requests from these ranges are logged as VPN.</div></div></div><div className="settings-grid"><div className="form-group"><label className="form-label">Emergency Super Admin email</label><input className="form-input" type="email" value={network.emergency_super_admin_email} onChange={e=>setNetwork({...network,emergency_super_admin_email:e.target.value})} placeholder="superadmin@example.org"/><div className="setting-help">Optional recovery bypass. Must be an existing Super Admin.</div></div><div className="setting-row"><div><div className="setting-title">Department Admin may manage external access</div><div className="setting-help">If enabled, Department Admin can allow/block External Internet for Operator/Viewer users inside its own department only.</div></div><Toggle checked={network.department_admin_can_manage_external_access} onChange={v=>setNetwork({...network,department_admin_can_manage_external_access:v})}/></div></div><button className="btn btn-primary" onClick={()=>save('network',{...network,allowed_cidrs:toLines(network.allowed_cidrs),trusted_vpn_proxies:toLines(network.trusted_vpn_proxies)})}><ShieldCheck size={14}/> Save Network Policy</button></div>

  <div className="settings-card"><h2 className="settings-card-title"><LockKeyhole size={18}/> Two-Factor Authentication</h2><div className="setting-row"><div><div className="setting-title">Enable TOTP two-factor authentication</div><div className="setting-help">Users can configure an authenticator and recovery codes from Profile.</div></div><Toggle checked={twoFactor.enabled} onChange={v=>setTwoFactor({...twoFactor,enabled:v})}/></div><div className="setting-row"><div><div className="setting-title">Require 2FA for Super Admin</div><div className="setting-help">Safe-enrollment guard prevents immediate administrator lockout.</div></div><Toggle checked={twoFactor.required_super_admin} onChange={v=>setTwoFactor({...twoFactor,required_super_admin:v})}/></div><div className="form-group"><label className="form-label">Authenticator issuer name</label><input className="form-input" value={twoFactor.issuer} onChange={e=>setTwoFactor({...twoFactor,issuer:e.target.value})}/></div><button className="btn btn-primary" onClick={()=>save('two_factor',twoFactor)}>Save Two-Factor Policy</button></div>

  <div className="settings-card"><h2 className="settings-card-title"><Image size={18}/> Watermark</h2><div className="setting-row"><div><div className="setting-title">Enable watermark support</div><div className="setting-help">Applies the configured user-identifiable/internal overlay according to file policy.</div></div><Toggle checked={watermark.enabled} onChange={v=>setWatermark({...watermark,enabled:v})}/></div><div className="settings-grid"><div className="form-group"><label className="form-label">Watermark text</label><input className="form-input" value={watermark.text} onChange={e=>setWatermark({...watermark,text:e.target.value})}/></div><div className="form-group"><label className="form-label">Opacity: {watermark.opacity}%</label><input style={{width:'100%'}} type="range" min={5} max={80} value={watermark.opacity} onChange={e=>setWatermark({...watermark,opacity:Number(e.target.value)})}/></div></div><label className="check-row"><input type="checkbox" checked={watermark.protected_only} onChange={e=>setWatermark({...watermark,protected_only:e.target.checked})}/>Protected content only</label><button className="btn btn-primary" onClick={()=>save('watermark',watermark)}>Save Watermark Policy</button></div>

  <div className="settings-card"><h2 className="settings-card-title"><ShieldCheck size={18}/> Lifecycle Workflow</h2><div className="setting-help">Choose which status transitions are allowed. The server still validates metadata before governed approval/publish transitions.</div><div style={{overflowX:'auto',marginTop:10}}><table className="admin-table"><thead><tr><th>From \ To</th>{statuses.map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{statuses.map(from=><tr key={from}><td><b>{from}</b></td>{statuses.map(to=><td key={to} style={{textAlign:'center'}}>{from===to?'—':<input type="checkbox" checked={(lifecycle[from]||[]).includes(to)} onChange={()=>toggleTransition(from,to)}/>}</td>)}</tr>)}</tbody></table></div><button className="btn btn-primary" style={{marginTop:10}} onClick={()=>save('lifecycle',{transitions:lifecycle})}>Save Lifecycle Workflow</button></div>

  <div className="settings-card"><h2 className="settings-card-title"><Languages size={18}/> Type-specific Mandatory Metadata</h2><div className="setting-help">Select extra fields that become mandatory for each media type in addition to the common metadata rules.</div><div className="role-admin-grid" style={{marginTop:10}}>{['video','image','audio','document'].map(type=><div className="role-admin-card" key={type}><b style={{textTransform:'capitalize'}}>{type}</b>{requiredFields.map(field=><label className="check-row" key={field}><input type="checkbox" checked={(typeRequired[type]||[]).includes(field)} onChange={()=>toggleRequired(type,field)}/>{fieldLabels[field]}</label>)}</div>)}</div><button className="btn btn-primary" style={{marginTop:10}} onClick={()=>save('type_required',typeRequired)}>Save Mandatory Fields</button></div>

  <div className="settings-grid"><div className="settings-card"><h2 className="settings-card-title"><ShieldOff size={18}/> Audit Retention</h2><div className="form-group"><label className="form-label">Retention days (0 = Policy Pending / no prune)</label><input className="form-input" type="number" min={0} value={auditRetention.retention_days} onChange={e=>setAuditRetention({...auditRetention,retention_days:Number(e.target.value)})}/></div><div className="form-group"><label className="form-label">Maximum records per run</label><input className="form-input" type="number" min={1} value={auditRetention.max_per_run} onChange={e=>setAuditRetention({...auditRetention,max_per_run:Number(e.target.value)})}/></div><label className="check-row"><input type="checkbox" checked={auditRetention.archive_before_prune} onChange={e=>setAuditRetention({...auditRetention,archive_before_prune:e.target.checked})}/>Archive before prune</label><button className="btn btn-primary" onClick={()=>save('audit_retention',auditRetention)}>Save Audit Retention</button></div>
  <div className="settings-card"><h2 className="settings-card-title"><Recycle size={18}/> Recycle Bin Retention</h2><div className="form-group"><label className="form-label">Retention days (0 = automatic purge OFF)</label><input className="form-input" type="number" min={0} value={recycleRetention.retention_days} onChange={e=>setRecycleRetention({...recycleRetention,retention_days:Number(e.target.value)})}/></div><div className="form-group"><label className="form-label">Maximum items per run</label><input className="form-input" type="number" min={1} value={recycleRetention.max_per_run} onChange={e=>setRecycleRetention({...recycleRetention,max_per_run:Number(e.target.value)})}/></div><button className="btn btn-primary" onClick={()=>save('recycle_retention',recycleRetention)}>Save Recycle Bin Retention</button></div></div>

  <div className="settings-card"><h2 className="settings-card-title"><Building2 size={18}/> Department Storage Quotas</h2><div className="admin-guide">Quota <b>0 GB</b> means unlimited / Management policy pending. Usage is calculated from physical stored bytes including active, Recycle Bin and historical versions.</div><div className="settings-grid"><div className="form-group"><label className="form-label">Default quota (GB)</label><input className="form-input" type="number" min={0} step="0.1" value={quota.default_quota_gb} onChange={e=>setQuota({...quota,default_quota_gb:Number(e.target.value)})}/></div><div className="form-group"><label className="form-label">Warning threshold (%)</label><input className="form-input" type="number" min={1} max={100} value={quota.warning_percent} onChange={e=>setQuota({...quota,warning_percent:Number(e.target.value)})}/></div></div><div className="role-admin-grid" style={{marginTop:10}}>{departments.filter(d=>d.is_active).map(d=><div className="form-group" key={d.id}><label className="form-label">{d.name} quota (GB)</label><input className="form-input" type="number" min={0} step="0.1" value={quota.departments[String(d.id)]??0} onChange={e=>setQuota({...quota,departments:{...quota.departments,[String(d.id)]:Number(e.target.value)}})}/></div>)}</div><button className="btn btn-primary" style={{marginTop:10}} onClick={()=>save('storage_quotas',quota)}>Save Storage Quotas</button></div>
 </div>
}
