import { useMemo, useState } from 'react';
import { router } from '@inertiajs/react';
import { Bell, CheckCheck, Mail, MessageCircle, ShieldAlert, Smartphone } from 'lucide-react';
import type { NotificationPreferences, PortalNotification } from '../../types';

interface Props { active:boolean; notifications:PortalNotification[]; unread:number; preferences:NotificationPreferences; onSuccess:(m:string)=>void; onError:(m:string)=>void; }
const csrf=()=>document.querySelector('meta[name="csrf-token"]')?.getAttribute('content')||'';
const Toggle=({checked,onChange}:{checked:boolean;onChange:(v:boolean)=>void})=><label className="toggle-switch"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><span className="toggle-track"/></label>;
function categoryOf(type:string){if(type.startsWith('access_'))return'access';if(type.includes('storage'))return'storage';if(type.includes('security')||type.includes('test_notification'))return'security';return'file'}

export default function NotificationsPanel({active,notifications,unread,preferences,onSuccess,onError}:Props){
 const [prefs,setPrefs]=useState<NotificationPreferences>({...preferences}); const [filter,setFilter]=useState<'all'|'unread'|'access'|'file'|'storage'|'security'>('all'); const [saving,setSaving]=useState(false);
 const rows=useMemo(()=>notifications.filter(n=>filter==='all'||(filter==='unread'&&!n.read_at)||(filter!=='unread'&&categoryOf(n.type)===filter)),[notifications,filter]);
 if(!active)return null;
 const markAll=async()=>{await fetch('/notifications/read-all',{method:'POST',headers:{'X-CSRF-TOKEN':csrf(),'Accept':'application/json'}});router.reload({only:['notifications','unreadNotifications']})};
 const markOne=async(n:PortalNotification)=>{if(n.read_at)return;await fetch(`/notifications/${n.id}/read`,{method:'PATCH',headers:{'X-CSRF-TOKEN':csrf(),'Accept':'application/json'}});router.reload({only:['notifications','unreadNotifications']})};
 const save=async()=>{setSaving(true);try{const r=await fetch('/notifications/preferences',{method:'PATCH',headers:{'X-CSRF-TOKEN':csrf(),'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify(prefs)});const d=await r.json();if(!r.ok)throw new Error(d.message||'Could not save preferences.');onSuccess(d.message||'Notification preferences saved.')}catch(e){onError(e instanceof Error?e.message:'Could not save preferences.')}finally{setSaving(false)}};
 return <section className="module-panel active"><div className="page-title-section"><div><h1 className="page-title"><Bell size={27} style={{color:'var(--color-primary)'}}/> Notification Center</h1><p className="page-subtitle">{unread} unread · Portal alerts plus your allowed external-channel preferences.</p></div><button className="btn btn-secondary" onClick={markAll}><CheckCheck size={15}/> Mark all read</button></div>
  <div className="settings-card" style={{marginBottom:16}}><h2 className="settings-card-title"><Bell size={18}/> My Notification Preferences</h2><div className="admin-guide">Central Admin master channel/event settings always take priority. Your preferences can reduce delivery, but cannot enable a channel disabled by Central Admin.</div><div className="settings-grid" style={{marginTop:12}}>
   {([['portal_enabled','Portal',<Bell size={16}/>],['email_enabled','Email',<Mail size={16}/>],['whatsapp_enabled','WhatsApp',<MessageCircle size={16}/>],['sms_enabled','Text SMS',<Smartphone size={16}/>]] as const).map(([key,label,icon])=><div className="setting-row" key={key}><div className="setting-title" style={{display:'flex',gap:7,alignItems:'center'}}>{icon}{label}</div><Toggle checked={prefs[key]} onChange={v=>setPrefs({...prefs,[key]:v})}/></div>)}
  </div><div className="settings-grid" style={{marginTop:8}}>{([['access_enabled','Access Requests'],['file_enabled','File Updates'],['storage_enabled','Storage / Broken Links'],['security_enabled','Security']] as const).map(([key,label])=><div className="setting-row" key={key}><div className="setting-title">{label}</div><Toggle checked={prefs[key]} onChange={v=>setPrefs({...prefs,[key]:v})}/></div>)}</div><button className="btn btn-primary" style={{marginTop:12}} disabled={saving} onClick={save}>{saving?'Saving…':'Save My Preferences'}</button></div>
  <div className="filter-bar" style={{marginBottom:12}}><div className="filter-left">{(['all','unread','access','file','storage','security'] as const).map(k=><button key={k} className={`filter-chip${filter===k?' active':''}`} onClick={()=>setFilter(k)}>{k.replace(/^./,c=>c.toUpperCase())}</button>)}</div></div>
  <div style={{display:'grid',gap:9}}>{rows.length===0?<div className="settings-card" style={{textAlign:'center',padding:30,color:'var(--text-muted)'}}>No notifications in this filter.</div>:rows.map(n=><button key={n.id} onClick={()=>markOne(n)} className="settings-card" style={{textAlign:'left',borderLeft:n.read_at?'3px solid transparent':'3px solid var(--color-primary)',display:'block',width:'100%'}}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><div className="setting-title">{n.title}</div><div className="setting-help" style={{marginTop:4,lineHeight:1.5}}>{n.message}</div></div><span className="card-tag" style={{height:'fit-content'}}>{categoryOf(n.type)}</span></div><div style={{fontSize:10,color:'var(--text-muted)',marginTop:7}}>{new Date(n.created_at).toLocaleString()} · {n.read_at?'Read':'Unread'}</div></button>)}</div>
 </section>;
}
