import { useEffect, useState } from 'react';
import { Activity, BellRing, CheckCircle2, Download, FileClock, Play, Plus, Printer, RefreshCcw, ShieldCheck, Trash2, Users } from 'lucide-react';
import type { NotificationDeliveryRow, ReportAuditRow, UserRole } from '../../types';

interface Props { active:boolean; role:UserRole; onError:(m:string)=>void; }
interface ScheduledRun { id:number; status:string; row_count:number; error:string|null; started_at:string|null; finished_at:string|null; download_url:string|null; }
interface ScheduledReportRow { id:number; name:string; report_type:string; frequency:'weekly'|'monthly'; format:'csv'|'xlsx'; is_active:boolean; recipient_user_id:number; recipient:{id:number;name:string;email:string}|null; department_id:number|null; last_run_at:string|null; next_run_at:string|null; runs:ScheduledRun[]; }
interface ScheduledData { enabled:boolean; reports:ScheduledReportRow[]; users:{id:number;name:string;email:string;department_id:number|null;role:string}[]; departments:{id:number;name:string}[]; }
const csrf=()=>document.querySelector('meta[name="csrf-token"]')?.getAttribute('content')||'';
function pretty(k:string){return k.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function Table({rows}:{rows:ReportAuditRow[]}){return <div style={{overflowX:'auto'}}><table className="report-table"><thead><tr><th>Date</th><th>User</th><th>Event</th><th>Subject</th><th>Description</th><th>IP / Source</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.created_at?new Date(r.created_at).toLocaleString():'-'}</td><td>{r.user}</td><td><code>{r.event}</code></td><td>{r.subject||'-'}</td><td>{r.description||'-'}</td><td>{r.ip_address||'-'}<br/><small>{r.source||'web'}</small></td></tr>)}</tbody></table></div>}

export default function ReportsPanel({active,role,onError}:Props){
 const [loading,setLoading]=useState(false),[summary,setSummary]=useState<Record<string,any>>({}),[access,setAccess]=useState<ReportAuditRow[]>([]),[activity,setActivity]=useState<ReportAuditRow[]>([]),[deliveries,setDeliveries]=useState<NotificationDeliveryRow[]>([]);
 const [scheduled,setScheduled]=useState<ScheduledData>({enabled:true,reports:[],users:[],departments:[]}),[scheduleMsg,setScheduleMsg]=useState(''),[scheduleBusy,setScheduleBusy]=useState(false);
 const [scheduleForm,setScheduleForm]=useState({name:'',report_type:'activity',frequency:'weekly',format:'csv',recipient_user_id:'',department_id:''});
 const load=async()=>{setLoading(true);try{const urls=['/reports/summary','/reports/access','/reports/activity',...(role==='super-admin'?['/reports/notifications','/scheduled-reports']:[])];const res=await Promise.all(urls.map(u=>fetch(u,{headers:{Accept:'application/json'}})));for(const r of res)if(!r.ok)throw new Error(`Report request failed (${r.status})`);const data=await Promise.all(res.map(r=>r.json()));setSummary(data[0]||{});setAccess(data[1]?.rows||[]);setActivity(data[2]?.rows||[]);if(role==='super-admin'){setDeliveries(data[3]?.rows||[]);setScheduled(data[4]||{enabled:true,reports:[],users:[],departments:[]})}}catch(e){onError(e instanceof Error?e.message:'Could not load reports.')}finally{setLoading(false)}};
 useEffect(()=>{if(active)void load()},[active,role]); if(!active)return null;
 const metricEntries=Object.entries(summary).filter(([k,v])=>!['role','audit_integrity'].includes(k)&&typeof v==='number');
 const verify=async()=>{try{const r=await fetch('/reports/audit/verify',{method:'POST',headers:{'X-CSRF-TOKEN':csrf(),'Accept':'application/json'}});const d=await r.json();if(!r.ok)throw new Error(d.message||'Verification failed');setSummary(s=>({...s,audit_integrity:d}))}catch(e){onError(e instanceof Error?e.message:'Verification failed')}};
 const scheduleRequest=async(url:string,method:string,body?:Record<string,unknown>)=>{setScheduleBusy(true);setScheduleMsg('');try{const r=await fetch(url,{method,headers:{'X-CSRF-TOKEN':csrf(),'Content-Type':'application/json','Accept':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw new Error(d.message||Object.values(d.errors||{}).flat().join('; ')||'Scheduled report request failed.');setScheduleMsg(d.message||'Scheduled report updated.');await load();return true}catch(e){const m=e instanceof Error?e.message:'Scheduled report request failed.';setScheduleMsg(m);onError(m);return false}finally{setScheduleBusy(false)}};
 const createSchedule=async()=>{if(!scheduleForm.name.trim()||!scheduleForm.recipient_user_id){setScheduleMsg('Name and recipient are required.');return;}const ok=await scheduleRequest('/scheduled-reports','POST',{name:scheduleForm.name.trim(),report_type:scheduleForm.report_type,frequency:scheduleForm.frequency,format:scheduleForm.format,recipient_user_id:Number(scheduleForm.recipient_user_id),department_id:scheduleForm.department_id?Number(scheduleForm.department_id):null});if(ok)setScheduleForm({name:'',report_type:'activity',frequency:'weekly',format:'csv',recipient_user_id:'',department_id:''})};
 return <section className="module-panel active"><div className="page-title-section"><div><h1 className="page-title"><Activity size={27} style={{color:'var(--color-primary)'}}/> Dashboards & Reports</h1><p className="page-subtitle">Role-scoped operational metrics, audit reports, exports and governed weekly/monthly schedules.</p></div><div style={{display:'flex',gap:8}}><button className="btn btn-secondary" onClick={()=>window.print()}><Printer size={14}/> Print / Save PDF</button><button className="btn btn-secondary" onClick={load}><RefreshCcw size={14}/> Refresh</button></div></div>
  {loading&&<div className="admin-guide">Loading report data…</div>}
  <div className="stats-grid">{metricEntries.map(([k,v],i)=><div className="stat-card" key={k}><div className="stat-info"><span className="stat-label">{pretty(k)}</span><span className="stat-value">{k.includes('storage')?`${((Number(v)||0)/1024/1024/1024).toFixed(2)} GB`:Number(v).toLocaleString()}</span></div><div className="stat-icon-wrapper">{i%3===0?<Users size={20}/>:i%3===1?<FileClock size={20}/>:<ShieldCheck size={20}/>}</div></div>)}</div>
  {role==='super-admin'&&summary.audit_integrity&&<div className="settings-card" style={{marginBottom:16}}><div className="setting-row"><div><div className="settings-card-title" style={{margin:0}}><ShieldCheck size={18}/> Audit Integrity</div><div className="setting-help">Hash chain: <b>{summary.audit_integrity.valid?'VALID':'INVALID'}</b> · checked {summary.audit_integrity.checked||0} records{summary.audit_integrity.invalid_id?` · first invalid #${summary.audit_integrity.invalid_id}`:''}</div></div><button className="btn btn-secondary" onClick={verify}><CheckCircle2 size={14}/> Verify Now</button></div></div>}

  {role==='super-admin'&&<div className="settings-card" style={{marginBottom:16}}><div className="setting-row"><div><h2 className="settings-card-title" style={{margin:0}}><FileClock size={18}/> Weekly / Monthly Scheduled Reports</h2><div className="setting-help">Scheduler policy: <b>{scheduled.enabled?'ENABLED':'DISABLED'}</b>. Due schedules are processed hourly by the Laravel scheduler container.</div></div></div>{scheduleMsg&&<div className="admin-guide" style={{marginTop:10}}>{scheduleMsg}</div>}
    <div className="settings-grid" style={{marginTop:12}}><label className="form-group"><span className="form-label">Schedule name</span><input className="form-input" value={scheduleForm.name} onChange={e=>setScheduleForm({...scheduleForm,name:e.target.value})} placeholder="Monthly management activity"/></label><label className="form-group"><span className="form-label">Report</span><select className="form-select" value={scheduleForm.report_type} onChange={e=>setScheduleForm({...scheduleForm,report_type:e.target.value})}><option value="activity">Activity / Security</option><option value="access">Access / Download</option><option value="notifications">Notification Delivery</option></select></label><label className="form-group"><span className="form-label">Frequency</span><select className="form-select" value={scheduleForm.frequency} onChange={e=>setScheduleForm({...scheduleForm,frequency:e.target.value})}><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label><label className="form-group"><span className="form-label">Format</span><select className="form-select" value={scheduleForm.format} onChange={e=>setScheduleForm({...scheduleForm,format:e.target.value})}><option value="csv">CSV</option><option value="xlsx">XLSX</option></select></label><label className="form-group"><span className="form-label">Recipient</span><select className="form-select" value={scheduleForm.recipient_user_id} onChange={e=>setScheduleForm({...scheduleForm,recipient_user_id:e.target.value})}><option value="">Select active user…</option>{scheduled.users.map(u=><option key={u.id} value={u.id}>{u.name} · {u.email}</option>)}</select></label><label className="form-group"><span className="form-label">Department scope</span><select className="form-select" value={scheduleForm.department_id} onChange={e=>setScheduleForm({...scheduleForm,department_id:e.target.value})}><option value="">All authorized scope</option>{scheduled.departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label></div><button className="btn btn-primary" style={{marginTop:10}} disabled={scheduleBusy||!scheduled.enabled} onClick={createSchedule}><Plus size={14}/> Create Schedule</button>
    <div style={{display:'grid',gap:9,marginTop:14}}>{scheduled.reports.length===0?<div className="setting-help">No scheduled reports configured.</div>:scheduled.reports.map(report=><div key={report.id} style={{border:'1px solid var(--border-color)',borderRadius:8,padding:11}}><div className="setting-row"><div><div className="setting-title">{report.name} · {report.frequency} · {report.format.toUpperCase()}</div><div className="setting-help">{report.report_type} · {report.recipient?.name||'Missing recipient'} · next {report.next_run_at?new Date(report.next_run_at).toLocaleString():'not scheduled'} · last {report.last_run_at?new Date(report.last_run_at).toLocaleString():'never'}</div></div><div style={{display:'flex',gap:6,flexWrap:'wrap'}}><button className="btn btn-secondary" disabled={scheduleBusy} onClick={()=>scheduleRequest(`/scheduled-reports/${report.id}`,'PATCH',{is_active:!report.is_active})}>{report.is_active?'Pause':'Enable'}</button><button className="btn btn-secondary" disabled={scheduleBusy||!report.is_active} onClick={()=>scheduleRequest(`/scheduled-reports/${report.id}/run`,'POST')}><Play size={12}/> Run now</button><button className="queue-remove-btn" disabled={scheduleBusy} onClick={()=>confirm(`Delete schedule “${report.name}”?`)&&scheduleRequest(`/scheduled-reports/${report.id}`,'DELETE')}><Trash2 size={13}/></button></div></div>{report.runs.length>0&&<div style={{display:'grid',gap:4,marginTop:8}}>{report.runs.map(run=><div key={run.id} className="setting-help">Run #{run.id} · <b>{run.status}</b> · {run.row_count} row(s){run.error?` · ${run.error}`:''}{run.download_url&&<> · <a href={run.download_url} className="auth-link">Download</a></>}</div>)}</div>}</div>)}</div>
  </div>}

  <div className="settings-card" style={{marginBottom:16}}><div className="setting-row"><div><h2 className="settings-card-title" style={{margin:0}}><ShieldCheck size={18}/> Access / Download Report</h2><div className="setting-help">Preview and download audit events within your authorized role scope.</div></div><a className="btn btn-secondary" href="/reports/export/access"><Download size={14}/> CSV</a></div><Table rows={access}/></div>
  <div className="settings-card" style={{marginBottom:16}}><div className="setting-row"><div><h2 className="settings-card-title" style={{margin:0}}><Activity size={18}/> Activity / Security Report</h2><div className="setting-help">Login, admin, access, file and configuration audit events.</div></div><a className="btn btn-secondary" href="/reports/export/activity"><Download size={14}/> CSV</a></div><Table rows={activity}/></div>
  {role==='super-admin'&&<div className="settings-card"><div className="setting-row"><div><h2 className="settings-card-title" style={{margin:0}}><BellRing size={18}/> Notification Delivery Report</h2><div className="setting-help">Queued, sent, skipped and failed provider deliveries.</div></div><a className="btn btn-secondary" href="/reports/export/notifications"><Download size={14}/> CSV</a></div><div style={{overflowX:'auto'}}><table className="report-table"><thead><tr><th>Date</th><th>User</th><th>Event</th><th>Channel</th><th>Recipient</th><th>Status</th><th>Attempts</th><th>Error</th></tr></thead><tbody>{deliveries.map(d=><tr key={d.id}><td>{d.created_at?new Date(d.created_at).toLocaleString():'-'}</td><td>{d.user||'System/Test'}</td><td>{d.event}</td><td>{d.channel}</td><td>{d.recipient||'-'}</td><td>{d.status}</td><td>{d.attempts}</td><td>{d.error||'-'}</td></tr>)}</tbody></table></div></div>}
 </section>;
}
