import { useEffect, useState } from 'react';
import { Activity, BellRing, CheckCircle2, Download, FileClock, Printer, RefreshCcw, ShieldCheck, Users } from 'lucide-react';
import type { NotificationDeliveryRow, ReportAuditRow, UserRole } from '../../types';

interface Props { active:boolean; role:UserRole; onError:(m:string)=>void; }
const csrf=()=>document.querySelector('meta[name="csrf-token"]')?.getAttribute('content')||'';
function pretty(k:string){return k.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function Table({rows}:{rows:ReportAuditRow[]}){return <div style={{overflowX:'auto'}}><table className="report-table"><thead><tr><th>Date</th><th>User</th><th>Event</th><th>Subject</th><th>Description</th><th>IP / Source</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.created_at?new Date(r.created_at).toLocaleString():'-'}</td><td>{r.user}</td><td><code>{r.event}</code></td><td>{r.subject||'-'}</td><td>{r.description||'-'}</td><td>{r.ip_address||'-'}<br/><small>{r.source||'web'}</small></td></tr>)}</tbody></table></div>}

export default function ReportsPanel({active,role,onError}:Props){
 const [loading,setLoading]=useState(false),[summary,setSummary]=useState<Record<string,any>>({}),[access,setAccess]=useState<ReportAuditRow[]>([]),[activity,setActivity]=useState<ReportAuditRow[]>([]),[deliveries,setDeliveries]=useState<NotificationDeliveryRow[]>([]);
 const load=async()=>{setLoading(true);try{const urls=['/reports/summary','/reports/access','/reports/activity',...(role==='super-admin'?['/reports/notifications']:[])];const res=await Promise.all(urls.map(u=>fetch(u,{headers:{Accept:'application/json'}})));for(const r of res)if(!r.ok)throw new Error(`Report request failed (${r.status})`);const data=await Promise.all(res.map(r=>r.json()));setSummary(data[0]||{});setAccess(data[1]?.rows||[]);setActivity(data[2]?.rows||[]);if(role==='super-admin')setDeliveries(data[3]?.rows||[])}catch(e){onError(e instanceof Error?e.message:'Could not load reports.')}finally{setLoading(false)}};
 useEffect(()=>{if(active)void load()},[active,role]); if(!active)return null;
 const metricEntries=Object.entries(summary).filter(([k,v])=>!['role','audit_integrity'].includes(k)&&typeof v==='number');
 const verify=async()=>{try{const r=await fetch('/reports/audit/verify',{method:'POST',headers:{'X-CSRF-TOKEN':csrf(),'Accept':'application/json'}});const d=await r.json();if(!r.ok)throw new Error(d.message||'Verification failed');setSummary(s=>({...s,audit_integrity:d}))}catch(e){onError(e instanceof Error?e.message:'Verification failed')}};
 return <section className="module-panel active"><div className="page-title-section"><div><h1 className="page-title"><Activity size={27} style={{color:'var(--color-primary)'}}/> Dashboards & Reports</h1><p className="page-subtitle">Role-scoped operational metrics, access/activity audit reports and approved CSV exports.</p></div><div style={{display:'flex',gap:8}}><button className="btn btn-secondary" onClick={()=>window.print()}><Printer size={14}/> Print / Save PDF</button><button className="btn btn-secondary" onClick={load}><RefreshCcw size={14}/> Refresh</button></div></div>
  {loading&&<div className="admin-guide">Loading report data…</div>}
  <div className="stats-grid">{metricEntries.map(([k,v],i)=><div className="stat-card" key={k}><div className="stat-info"><span className="stat-label">{pretty(k)}</span><span className="stat-value">{k.includes('storage')?`${((Number(v)||0)/1024/1024/1024).toFixed(2)} GB`:Number(v).toLocaleString()}</span></div><div className="stat-icon-wrapper">{i%3===0?<Users size={20}/>:i%3===1?<FileClock size={20}/>:<ShieldCheck size={20}/>}</div></div>)}</div>
  {role==='super-admin'&&summary.audit_integrity&&<div className="settings-card" style={{marginBottom:16}}><div className="setting-row"><div><div className="settings-card-title" style={{margin:0}}><ShieldCheck size={18}/> Audit Integrity</div><div className="setting-help">Hash chain: <b>{summary.audit_integrity.valid?'VALID':'INVALID'}</b> · checked {summary.audit_integrity.checked||0} records{summary.audit_integrity.invalid_id?` · first invalid #${summary.audit_integrity.invalid_id}`:''}</div></div><button className="btn btn-secondary" onClick={verify}><CheckCircle2 size={14}/> Verify Now</button></div></div>}
  <div className="settings-card" style={{marginBottom:16}}><div className="setting-row"><div><h2 className="settings-card-title" style={{margin:0}}><ShieldCheck size={18}/> Access / Download Report</h2><div className="setting-help">Preview and download audit events within your authorized role scope.</div></div><a className="btn btn-secondary" href="/reports/export/access"><Download size={14}/> CSV</a></div><Table rows={access}/></div>
  <div className="settings-card" style={{marginBottom:16}}><div className="setting-row"><div><h2 className="settings-card-title" style={{margin:0}}><Activity size={18}/> Activity / Security Report</h2><div className="setting-help">Login, admin, access, file and configuration audit events.</div></div><a className="btn btn-secondary" href="/reports/export/activity"><Download size={14}/> CSV</a></div><Table rows={activity}/></div>
  {role==='super-admin'&&<div className="settings-card"><div className="setting-row"><div><h2 className="settings-card-title" style={{margin:0}}><BellRing size={18}/> Notification Delivery Report</h2><div className="setting-help">Queued, sent, skipped and failed provider deliveries.</div></div><a className="btn btn-secondary" href="/reports/export/notifications"><Download size={14}/> CSV</a></div><div style={{overflowX:'auto'}}><table className="report-table"><thead><tr><th>Date</th><th>User</th><th>Event</th><th>Channel</th><th>Recipient</th><th>Status</th><th>Attempts</th><th>Error</th></tr></thead><tbody>{deliveries.map(d=><tr key={d.id}><td>{d.created_at?new Date(d.created_at).toLocaleString():'-'}</td><td>{d.user||'System/Test'}</td><td>{d.event}</td><td>{d.channel}</td><td>{d.recipient||'-'}</td><td>{d.status}</td><td>{d.attempts}</td><td>{d.error||'-'}</td></tr>)}</tbody></table></div></div>}
 </section>;
}
