import { useEffect, useMemo, useState } from 'react';
import { Download, FileCheck2, PlayCircle, Printer, RefreshCw, ShieldCheck, TriangleAlert, XCircle, CheckCircle2, Clock3 } from 'lucide-react';
import type { GoLiveSettings, ManagementDependency, ReadinessData, ReadinessSnapshotRow, UatCaseRow, UatStatus } from '../../types';

interface Props { data:ReadinessData; onSuccess:(message:string)=>void; onError:(message:string)=>void; }
const csrf=()=>document.querySelector('meta[name="csrf-token"]')?.getAttribute('content')||'';
async function req(url:string,method:string,body?:unknown){const r=await fetch(url,{method,headers:{'X-CSRF-TOKEN':csrf(),'Content-Type':'application/json','Accept':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||`HTTP ${r.status}`);return d;}
const fmt=(v:string|null)=>v?new Date(v).toLocaleString():'—';
const statusLabel=(s:string)=>s.replaceAll('-',' ').replace(/\b\w/g,c=>c.toUpperCase());

export default function UatReadinessPanel({data,onSuccess,onError}:Props){
 const [uat,setUat]=useState<UatCaseRow[]>(data.uat_cases||[]); const [settings,setSettings]=useState<GoLiveSettings>({...data.go_live_settings});
 const [deps,setDeps]=useState<ManagementDependency[]>((data.management_dependencies||[]).map(x=>({...x}))); const [snapshot,setSnapshot]=useState<ReadinessSnapshotRow|null>(data.latest_snapshot||null); const [latestReview,setLatestReview]=useState(data.latest_review||null);
 const [busy,setBusy]=useState(''); const [reviewNotes,setReviewNotes]=useState(''); const [dirtyCases,setDirtyCases]=useState<Set<number>>(new Set());
 useEffect(()=>{setUat(data.uat_cases||[]);setSettings({...data.go_live_settings});setDeps((data.management_dependencies||[]).map(x=>({...x})));setSnapshot(data.latest_snapshot||null);setLatestReview(data.latest_review||null);setDirtyCases(new Set())},[data]);
 const counts=useMemo(()=>({passed:uat.filter(x=>x.status==='passed').length,approved:uat.filter(x=>x.status==='passed'&&x.approved_at&&x.approved_app_version===data.app_version).length,failed:uat.filter(x=>['failed','blocked'].includes(x.status)).length,total:uat.length}),[uat,data.app_version]);
 const updateCase=(id:number,patch:Partial<UatCaseRow>)=>{setUat(xs=>xs.map(x=>x.id===id?{...x,...patch}:x));setDirtyCases(prev=>{const next=new Set(prev);next.add(id);return next})};
 const saveCase=async(c:UatCaseRow)=>{setBusy(`case-${c.id}`);try{const d=await req(`/settings/readiness/uat/${c.id}`,'PATCH',{status:c.status,execution_notes:c.execution_notes||'',evidence_reference:c.evidence_reference||''});setUat(xs=>xs.map(x=>x.id===c.id?d.case:x));setDirtyCases(prev=>{const next=new Set(prev);next.delete(c.id);return next});onSuccess(d.message)}catch(e){onError(e instanceof Error?e.message:'Could not save UAT case')}finally{setBusy('')}};
 const approveCase=async(c:UatCaseRow)=>{if(dirtyCases.has(c.id))return onError('Save the current UAT result before sign-off.');if(c.executed_app_version!==data.app_version)return onError(`Re-run and save ${c.code} against v${data.app_version} before sign-off.`);if(!confirm(`Approve/sign-off ${c.code} as passed for v${data.app_version}?`))return;setBusy(`approve-${c.id}`);try{const d=await req(`/settings/readiness/uat/${c.id}/approve`,'POST',{});updateCase(c.id,d.case);onSuccess(d.message)}catch(e){onError(e instanceof Error?e.message:'UAT approval failed')}finally{setBusy('')}};
 const runChecks=async()=>{setBusy('checks');try{const d=await req('/settings/readiness/run','POST',{});setSnapshot(d.snapshot);onSuccess(`Readiness checks: ${statusLabel(d.summary.overall_status)} · ${d.summary.blocking_failures} blocking failure(s).`)}catch(e){onError(e instanceof Error?e.message:'Readiness checks failed')}finally{setBusy('')}};
 const saveSettings=async()=>{setBusy('settings');try{const d=await req('/settings/readiness/go-live','PATCH',settings);setSettings(d.settings);onSuccess(d.message)}catch(e){onError(e instanceof Error?e.message:'Could not save go-live settings')}finally{setBusy('')}};
 const saveDeps=async()=>{setBusy('deps');try{const d=await req('/settings/readiness/dependencies','PATCH',{dependencies:deps});setDeps(d.dependencies);onSuccess(d.message)}catch(e){onError(e instanceof Error?e.message:'Could not save dependencies')}finally{setBusy('')}};
 const review=async(decision:'approved'|'rejected')=>{if(decision==='approved'&&!confirm('APPROVE GO-LIVE? The server will refuse approval if any blocking readiness gate remains.'))return;setBusy(`review-${decision}`);try{const d=await req('/settings/readiness/review','POST',{decision,notes:reviewNotes});setLatestReview(d.review);onSuccess(d.message);setReviewNotes('');await runChecks()}catch(e){onError(e instanceof Error?e.message:'Go-live review failed')}finally{setBusy('')}};
 const checkIcon=(s:string)=>s==='pass'?<CheckCircle2 size={16}/>:s==='fail'?<XCircle size={16}/>:<TriangleAlert size={16}/>;
 return <div className="readiness-panel" style={{display:'grid',gap:18}}>
   <div className="settings-card"><div className="readiness-title-row"><div><h2 className="settings-card-title"><ShieldCheck size={19}/> UAT & Go-Live Readiness</h2><div className="setting-help">v{data.app_version} provides an evidence-based production gate. UAT execution/sign-off is release-bound: prior-release approvals do not satisfy the current gate.</div></div><div className={`readiness-overall ${snapshot?.overall_status||'not-run'}`}>{snapshot?statusLabel(snapshot.overall_status):'Checks Not Run'}</div></div>
    <div className="readiness-kpis"><div><b>{counts.passed}/{counts.total}</b><span>UAT Passed</span></div><div><b>{counts.approved}/{counts.total}</b><span>Signed Off</span></div><div><b>{snapshot?.summary?.blocking_failures??'—'}</b><span>Blocking Checks</span></div><div><b>{deps.filter(x=>x.status==='pending').length}</b><span>Pending Decisions</span></div></div>
    <div className="readiness-actions"><button className="btn btn-primary" disabled={busy==='checks'} onClick={runChecks}><RefreshCw size={15}/>{busy==='checks'?' Running…':' Run Automated Checks'}</button><a className="btn btn-secondary" href="/settings/readiness/export.csv"><Download size={15}/> Export CSV</a><button className="btn btn-secondary" onClick={()=>window.print()}><Printer size={15}/> Print / Save PDF</button></div>
    {snapshot&&<div className="setting-help" style={{marginTop:8}}>Last run: {fmt(snapshot.run_at)} · v{snapshot.app_version||'—'} · {snapshot.run_by||'System'} · {snapshot.summary.passes}/{snapshot.summary.total} pass · {snapshot.summary.warnings} warning(s)</div>}
   </div>

   {snapshot&&<div className="settings-card"><h2 className="settings-card-title"><PlayCircle size={18}/> Automated Environment Checks</h2><div className="readiness-checks">{snapshot.checks.map(c=><div key={c.key} className={`readiness-check ${c.status}`}><div className="readiness-check-icon">{checkIcon(c.status)}</div><div><div className="setting-title">{c.label} {c.blocking&&<span className="readiness-blocking">BLOCKING</span>}</div><div className="setting-help">{c.detail}</div></div></div>)}</div></div>}

   <div className="settings-card"><h2 className="settings-card-title"><FileCheck2 size={18}/> P0 UAT Matrix & Evidence</h2><div className="admin-guide"><b>Workflow:</b> run the case in staging → record result + notes/evidence → save → a Super Admin signs off a Passed case. Changing a signed case resets approval so evidence cannot silently drift.</div><div className="uat-case-list">{uat.map(c=><div className={`uat-case ${c.status}`} key={c.id}><div className="uat-case-head"><div><b>{c.code}</b><span>{c.category}</span></div><div>{c.approved_at?<span className="uat-approved"><ShieldCheck size={13}/> Signed {fmt(c.approved_at)}</span>:<span className="setting-help">Not signed</span>}</div></div><div className="uat-title">{c.title}</div><div className="uat-grid"><label>Result<select value={c.status} onChange={e=>updateCase(c.id,{status:e.target.value as UatStatus})}><option value="pending">Pending</option><option value="wip">In Progress</option><option value="passed">Passed</option><option value="failed">Failed</option><option value="blocked">Blocked</option></select></label><label>Evidence reference<input value={c.evidence_reference||''} onChange={e=>updateCase(c.id,{evidence_reference:e.target.value})} placeholder="Ticket / test report / screenshot path / sign-off reference"/></label></div><label className="uat-notes">Execution notes / observed result<textarea rows={3} value={c.execution_notes||''} onChange={e=>updateCase(c.id,{execution_notes:e.target.value})} placeholder="Environment, test steps/result, defects or evidence summary…"/></label><div className="uat-case-footer"><span className="setting-help">Executed: {fmt(c.executed_at)} {c.executed_by?`· ${c.executed_by}`:''} {c.executed_app_version?`· v${c.executed_app_version}`:''}{dirtyCases.has(c.id)?' · Unsaved changes':''}</span><div><button className="btn btn-secondary" disabled={busy===`case-${c.id}`} onClick={()=>saveCase(c)}>{busy===`case-${c.id}`?'Saving…':'Save Result'}</button>{c.status==='passed'&&!c.approved_at&&<button className="btn btn-primary" disabled={busy===`approve-${c.id}`||dirtyCases.has(c.id)||c.executed_app_version!==data.app_version} onClick={()=>approveCase(c)}><ShieldCheck size={14}/> Sign Off v{data.app_version}</button>}</div></div></div>)}</div></div>

   <div className="settings-card"><h2 className="settings-card-title"><TriangleAlert size={18}/> Management Dependencies</h2><div className="admin-guide">A dependency can be <b>Resolved</b> or formally <b>Risk Accepted</b>. Non-Pending decisions require a decision/owner/approval-reference note; blank formal decisions are rejected.</div><div className="dependency-list">{deps.map((d,i)=><div className="dependency-row" key={d.key}><div><div className="setting-title">{d.label}</div><div className="setting-help">{d.key}</div></div><select value={d.status} onChange={e=>setDeps(xs=>xs.map((x,j)=>j===i?{...x,status:e.target.value as ManagementDependency['status']}:x))}><option value="pending">Pending</option><option value="resolved">Resolved</option><option value="accepted-risk">Risk Accepted</option></select><input className={d.status!=='pending'&&!d.note.trim()?'input-error':''} value={d.note||''} onChange={e=>setDeps(xs=>xs.map((x,j)=>j===i?{...x,note:e.target.value}:x))} placeholder={d.status==='pending'?'Optional while Pending':'Required: decision / owner / approval reference'}/></div>)}</div><button className="btn btn-primary" disabled={busy==='deps'} onClick={saveDeps}>{busy==='deps'?'Saving…':'Save Dependency Status'}</button></div>

   <div className="settings-card"><h2 className="settings-card-title"><Clock3 size={18}/> Go-Live Runbook Ownership</h2><div className="settings-grid"><div><label className="form-label">Planned go-live date/time</label><input className="form-input" type="datetime-local" value={settings.planned_go_live_at||''} onChange={e=>setSettings({...settings,planned_go_live_at:e.target.value})}/></div><div><label className="form-label">Deployment owner</label><input className="form-input" value={settings.deployment_owner||''} onChange={e=>setSettings({...settings,deployment_owner:e.target.value})}/></div><div><label className="form-label">Rollback owner</label><input className="form-input" value={settings.rollback_owner||''} onChange={e=>setSettings({...settings,rollback_owner:e.target.value})}/></div><div><label className="form-label">Business sign-off owner</label><input className="form-input" value={settings.business_signoff_owner||''} onChange={e=>setSettings({...settings,business_signoff_owner:e.target.value})}/></div><div><label className="form-label">Smoke-test owner</label><input className="form-input" value={settings.smoke_test_owner||''} onChange={e=>setSettings({...settings,smoke_test_owner:e.target.value})}/></div><div><label className="form-label">Support / escalation contact</label><input className="form-input" value={settings.support_contact||''} onChange={e=>setSettings({...settings,support_contact:e.target.value})}/></div><div><label className="form-label">Rollback decision window (minutes)</label><input className="form-input" type="number" min={0} value={settings.rollback_window_minutes||0} onChange={e=>setSettings({...settings,rollback_window_minutes:Number(e.target.value)})}/><div className="setting-help">0 = policy not yet approved.</div></div></div><label className="setting-row" style={{marginTop:12}}><div><div className="setting-title">Production change freeze confirmed</div><div className="setting-help">Confirm approved scope/version is frozen before final go-live approval.</div></div><input type="checkbox" checked={Boolean(settings.change_freeze_confirmed)} onChange={e=>setSettings({...settings,change_freeze_confirmed:e.target.checked})}/></label><button className="btn btn-primary" disabled={busy==='settings'} onClick={saveSettings}>{busy==='settings'?'Saving…':'Save Go-Live Ownership'}</button></div>

   <div className="settings-card go-live-decision"><h2 className="settings-card-title"><ShieldCheck size={18}/> Final Go-Live Review</h2><div className="admin-guide">The server creates a fresh readiness snapshot at decision time. <b>Approve</b> is refused unless every blocking check passes, every UAT case is Passed + signed off, Management dependencies are resolved/risk-accepted, required owners are recorded, and change freeze is confirmed.</div>{latestReview&&<div className={`latest-review ${latestReview.decision}`}><b>Latest review: {statusLabel(latestReview.decision)} · v{latestReview.app_version||'—'}</b><span>{fmt(latestReview.reviewed_at)} · {latestReview.reviewed_by||'—'}</span>{latestReview.notes&&<p>{latestReview.notes}</p>}</div>}<label className="form-label">Review / sign-off notes</label><textarea className="form-input" rows={4} value={reviewNotes} onChange={e=>setReviewNotes(e.target.value)} placeholder="Go-live approval reference, CAB/manager sign-off, exceptions, rollback conditions…"/><div className="readiness-actions" style={{marginTop:10}}><button className="btn btn-secondary" disabled={busy==='review-rejected'} onClick={()=>review('rejected')}><XCircle size={15}/> Record Not Ready / Rejected</button><button className="btn btn-primary" disabled={busy==='review-approved'} onClick={()=>review('approved')}><ShieldCheck size={15}/> APPROVE GO-LIVE</button></div></div>
 </div>;
}
