import { useMemo, useState } from 'react';
import { router } from '@inertiajs/react';
import { CheckCircle2, Globe2, KeyRound, Mail, Plus, RefreshCcw, ShieldCheck, Trash2, UserCog, UserPlus, Users, WifiOff } from 'lucide-react';
import type { Department, NetworkPolicySummary, OrganizationUnit, PageAccessKey, PortalRole, User, UserGroup, UserRole } from '../../types';

interface Props {
  currentUser:User;
  users:User[];
  departments:Department[];
  organizationUnits:OrganizationUnit[];
  portalRoles:PortalRole[];
  userGroups:UserGroup[];
  networkPolicy:NetworkPolicySummary;
  onSuccess:(m:string)=>void;
  onError:(m:string)=>void;
}

const pageLabels:Record<PageAccessKey,string>={browse:'Browse Files',upload:'Batch Upload',access:'Access Requests',reports:'Dashboards & Reports',integrations:'Integrations & Health',guide:'User Guide Manual',settings:'Settings'};
const permissionLabels:Record<string,string>={upload:'Upload files',delete:'Archive / delete',manage_policy:'Manage access policy',manage_lifecycle:'Manage lifecycle',review_access:'Review access requests',manage_categories:'Manage categories'};
const baseRoleLabels:Record<UserRole,string>={'super-admin':'Super Admin','department-admin':'Department Admin','department-operator':'Department Operator','viewer':'Viewer'};
const csrf=()=>document.querySelector('meta[name="csrf-token"]')?.getAttribute('content')||'';
async function api(url:string,method:string,body:Record<string,unknown>={}){
  const r=await fetch(url,{method,headers:{'X-CSRF-TOKEN':csrf(),'Content-Type':'application/json','Accept':'application/json'},body:method==='GET'?undefined:JSON.stringify(body)});
  const d=await r.json().catch(()=>({}));
  if(!r.ok){const first=Object.values((d.errors||{}) as Record<string,string|string[]>)[0];const detail=Array.isArray(first)?first[0]:first;throw new Error(String(d.message||detail||`HTTP ${r.status}`));}
  return d;
}
function dtLocal(value?:string|null){if(!value)return'';const d=new Date(value);const z=(n:number)=>String(n).padStart(2,'0');return`${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`}

export default function UserRoleManagementPanel(p:Props){
  const isSuper=p.currentUser.role==='super-admin';
  const manageableRoles=useMemo(()=>p.portalRoles.filter(r=>r.is_active&&(isSuper||!['super-admin','department-admin'].includes(r.base_role))),[p.portalRoles,isSuper]);
  const activeDepartments=p.departments.filter(d=>d.is_active);
  const [name,setName]=useState(''),[email,setEmail]=useState(''),[phone,setPhone]=useState(''),[departmentId,setDepartmentId]=useState(isSuper?'':String(p.currentUser.department_id||'')),[unitId,setUnitId]=useState(''),[roleId,setRoleId]=useState('');
  const [roleName,setRoleName]=useState(''),[roleBase,setRoleBase]=useState<UserRole>('viewer');
  const [rolePages,setRolePages]=useState<Record<PageAccessKey,boolean>>({browse:true,upload:false,access:true,reports:true,integrations:false,guide:true,settings:false});
  const [rolePermissions,setRolePermissions]=useState<Record<string,boolean>>({upload:false,delete:false,manage_policy:false,manage_lifecycle:false,review_access:false,manage_categories:false});
  const [groupName,setGroupName]=useState(''),[groupDescription,setGroupDescription]=useState(''),[groupDept,setGroupDept]=useState(isSuper?'':String(p.currentUser.department_id||'')),[groupRole,setGroupRole]=useState(''),[groupMember,setGroupMember]=useState<Record<number,string>>({});
  const [externalDraft,setExternalDraft]=useState<Record<number,{allowed:boolean;starts_at:string;expires_at:string;reason:string}>>({});

  const deptUnits=p.organizationUnits.filter(u=>u.is_active&&String(u.department_id)===departmentId);
  const refresh=()=>router.reload({only:['users','portalRoles','userGroups','networkPolicySummary','currentUser']});

  const createUser=async()=>{
    if(!name.trim()||!email.trim()||!roleId)return p.onError('Name, email and role are required.');
    try{const d=await api('/users','POST',{name:name.trim(),email:email.trim(),phone:phone.trim()||null,department_id:departmentId?Number(departmentId):null,organization_unit_id:unitId?Number(unitId):null,portal_role_id:Number(roleId),send_reset_email:true});p.onSuccess(d.message);setName('');setEmail('');setPhone('');setUnitId('');refresh();}catch(e){p.onError(e instanceof Error?e.message:'Could not create user.');}
  };
  const assignRole=async(u:User,id:string)=>{try{const d=await api(`/users/${u.id}/portal-role`,'PATCH',{portal_role_id:Number(id)});p.onSuccess(d.message);refresh();}catch(e){p.onError(e instanceof Error?e.message:'Role assignment failed.')}};
  const setStatus=async(u:User,status:'active'|'disabled'|'inactive')=>{if(!isSuper)return;const reason=status==='active'?'Reactivated by Super Admin':prompt(`Reason for ${status}:`)?.trim();if(status!=='active'&&!reason)return;try{const d=await api(`/users/${u.id}/status`,'PATCH',{status,reason:reason||null});p.onSuccess(d.message);refresh();}catch(e){p.onError(e instanceof Error?e.message:'Status update failed.')}};
  const resetPassword=async(u:User)=>{if(!confirm(`Send password reset email to ${u.email}?`))return;try{const d=await api(`/users/${u.id}/password-reset`,'POST');p.onSuccess(d.message);}catch(e){p.onError(e instanceof Error?e.message:'Password reset email failed.')}};
  const resetAll=async()=>{if(!isSuper||!confirm('Send password-reset emails to ALL active users except yourself?'))return;try{const d=await api('/users/password-reset-all','POST',{confirm:true});p.onSuccess(d.message);}catch(e){p.onError(e instanceof Error?e.message:'Bulk reset failed.')}};

  const draftFor=(u:User)=>externalDraft[u.id]||{allowed:Boolean(u.external_access_allowed),starts_at:dtLocal(u.external_access_starts_at),expires_at:dtLocal(u.external_access_expires_at),reason:u.external_access_reason||''};
  const setDraft=(u:User,next:Partial<{allowed:boolean;starts_at:string;expires_at:string;reason:string}>)=>setExternalDraft(x=>({...x,[u.id]:{...draftFor(u),...next}}));
  const saveExternal=async(u:User)=>{const d=draftFor(u);try{const r=await api(`/users/${u.id}/external-access`,'PATCH',{allowed:d.allowed,starts_at:d.starts_at||null,expires_at:d.expires_at||null,reason:d.reason||null});p.onSuccess(r.message);setExternalDraft(x=>{const n={...x};delete n[u.id];return n});refresh();}catch(e){p.onError(e instanceof Error?e.message:'External access update failed.')}};

  const createRole=async()=>{if(!isSuper||!roleName.trim())return p.onError('Role name is required.');try{const d=await api('/portal-roles','POST',{name:roleName.trim(),base_role:roleBase,page_access:rolePages,permissions:rolePermissions});p.onSuccess(d.message);setRoleName('');refresh();}catch(e){p.onError(e instanceof Error?e.message:'Could not create role.')}};
  const saveRole=async(r:PortalRole,patch:Partial<PortalRole>)=>{if(!isSuper)return;const next={...r,...patch};try{const d=await api(`/portal-roles/${r.id}`,'PATCH',{name:next.name,base_role:next.base_role,is_active:next.is_builtin?true:next.is_active,page_access:next.page_access,permissions:next.permissions});p.onSuccess(d.message);refresh();}catch(e){p.onError(e instanceof Error?e.message:'Role update failed.')}};
  const deleteRole=async(r:PortalRole)=>{if(!isSuper||r.is_builtin||!confirm(`Delete custom role “${r.name}”?`))return;try{const d=await api(`/portal-roles/${r.id}`,'DELETE');p.onSuccess(d.message);refresh();}catch(e){p.onError(e instanceof Error?e.message:'Role delete failed.')}};

  const createGroup=async()=>{if(!groupName.trim())return p.onError('Group name is required.');try{const d=await api('/user-groups','POST',{name:groupName.trim(),description:groupDescription.trim()||null,department_id:groupDept?Number(groupDept):null,portal_role_id:groupRole?Number(groupRole):null});p.onSuccess(d.message);setGroupName('');setGroupDescription('');refresh();}catch(e){p.onError(e instanceof Error?e.message:'Could not create group.')}};
  const addGroupMember=async(g:UserGroup)=>{const id=groupMember[g.id];if(!id)return p.onError('Choose a user.');try{const d=await api(`/user-groups/${g.id}/members`,'POST',{user_id:Number(id),apply_group_role:true});p.onSuccess(d.message);setGroupMember(x=>({...x,[g.id]:''}));refresh();}catch(e){p.onError(e instanceof Error?e.message:'Could not add user to group.')}};
  const removeGroupMember=async(g:UserGroup,u:User)=>{try{const d=await api(`/user-groups/${g.id}/members/${u.id}`,'DELETE');p.onSuccess(d.message);refresh();}catch(e){p.onError(e instanceof Error?e.message:'Could not remove group member.')}};
  const applyGroupRole=async(g:UserGroup)=>{if(!confirm(`Apply ${g.portal_role?.name||'group role'} to all active members of ${g.name}?`))return;try{const d=await api(`/user-groups/${g.id}/apply-role`,'POST');p.onSuccess(d.message);refresh();}catch(e){p.onError(e instanceof Error?e.message:'Could not apply group role.')}};
  const deleteGroup=async(g:UserGroup)=>{if(!confirm(`Delete group “${g.name}”? Users will not be deleted.`))return;try{const d=await api(`/user-groups/${g.id}`,'DELETE');p.onSuccess(d.message);refresh();}catch(e){p.onError(e instanceof Error?e.message:'Could not delete group.')}};

  const canManageExternal=isSuper||p.networkPolicy.department_admin_can_manage_external_access;
  return <div style={{display:'grid',gap:18}}>
    <div className="admin-guide"><b>Users & Roles:</b> Create users, assign built-in/custom roles, organize users into groups, send password reset emails and govern external Internet exceptions. Default network posture remains <b>Internal / VPN Only</b>.</div>

    <div className="settings-card"><h2 className="settings-card-title"><UserPlus size={18}/> Create User</h2><div className="setting-help">A random unusable password is generated and a single-use setup/reset link is emailed. Department Admin can create users only inside the current department and only with Operator/Viewer based roles.</div><div className="settings-grid" style={{marginTop:12}}>
      <div className="form-group"><label className="form-label">Full Name</label><input className="form-input" value={name} onChange={e=>setName(e.target.value)} placeholder="User name"/></div>
      <div className="form-group"><label className="form-label">Email</label><input className="form-input" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="user@example.org"/></div>
      <div className="form-group"><label className="form-label">Phone</label><input className="form-input" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Optional"/></div>
      <div className="form-group"><label className="form-label">Department</label><select className="form-select" disabled={!isSuper} value={departmentId} onChange={e=>{setDepartmentId(e.target.value);setUnitId('')}}><option value="">No department</option>{activeDepartments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></div>
      <div className="form-group"><label className="form-label">Sub-department / Team</label><select className="form-select" value={unitId} onChange={e=>setUnitId(e.target.value)}><option value="">None</option>{deptUnits.map(u=><option key={u.id} value={u.id}>{u.type==='team'?'Team':'Sub-department'} · {u.name}</option>)}</select></div>
      <div className="form-group"><label className="form-label">Role</label><select className="form-select" value={roleId} onChange={e=>setRoleId(e.target.value)}><option value="">Choose role…</option>{manageableRoles.map(r=><option key={r.id} value={r.id}>{r.name}{r.is_builtin?'':' (Custom)'}</option>)}</select></div>
    </div><button className="btn btn-primary" style={{marginTop:12}} onClick={createUser}><Plus size={15}/> Create User & Email Setup Link</button></div>

    <div className="settings-card"><div className="setting-row"><div><h2 className="settings-card-title" style={{margin:0}}><UserCog size={18}/> User Management</h2><div className="setting-help">Super Admin can enable/disable all users. Department Admin can manage password reset and, when delegated, external access for its own users.</div></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><a className="btn btn-secondary" href="/users/export/csv">Export CSV</a>{isSuper&&<button className="btn btn-secondary" onClick={resetAll}><Mail size={14}/> Reset Passwords for All Active Users</button>}</div></div>
      <div className="user-admin-grid" style={{marginTop:12}}>{p.users.map(u=>{const d=draftFor(u);const roleOptions=manageableRoles.filter(r=>isSuper||!['super-admin','department-admin'].includes(r.base_role));return <article className="user-admin-card" key={u.id}><div className="user-admin-head"><div><b>{u.name}</b><div className="setting-help">{u.email} · {u.department?.name||'No department'}</div></div><span className={`status-pill ${u.status||'active'}`}>{u.status||'active'}</span></div><div className="user-admin-meta"><span>{u.portal_role?.name||baseRoleLabels[u.role]}</span><span>{(u.groups||[]).map(g=>g.name).join(', ')||'No group'}</span></div>
        <div className="form-group"><label className="form-label">Assigned Role</label><select className="form-select" disabled={u.id===p.currentUser.id} value={u.portal_role_id||''} onChange={e=>assignRole(u,e.target.value)}><option value="">Choose role…</option>{roleOptions.map(r=><option key={r.id} value={r.id}>{r.name}{r.is_builtin?'':' (Custom)'}</option>)}</select></div>
        <div style={{display:'flex',gap:7,flexWrap:'wrap',marginTop:8}}><button className="btn btn-secondary" onClick={()=>resetPassword(u)}><KeyRound size={13}/> Send Password Reset</button>{isSuper&&u.id!==p.currentUser.id&&<select className="form-select" style={{width:135}} value={u.status||'active'} onChange={e=>setStatus(u,e.target.value as 'active'|'disabled'|'inactive')}><option value="active">Active</option><option value="disabled">Disabled</option><option value="inactive">Inactive</option></select>}</div>
        <div className="external-access-box"><div className="setting-row"><div><div className="setting-title"><Globe2 size={14}/> External Internet Access</div><div className="setting-help">{u.external_access_allowed?'Exception configured':'Internal / VPN Only'}</div></div>{canManageExternal?<label className="toggle-switch"><input type="checkbox" checked={d.allowed} onChange={e=>setDraft(u,{allowed:e.target.checked})}/><span className="toggle-track"/></label>:<WifiOff size={18}/>}</div>{canManageExternal&&<><div className="settings-grid compact"><div className="form-group"><label className="form-label">Start</label><input className="form-input" type="datetime-local" value={d.starts_at} onChange={e=>setDraft(u,{starts_at:e.target.value})}/></div><div className="form-group"><label className="form-label">Expiry (optional)</label><input className="form-input" type="datetime-local" value={d.expires_at} onChange={e=>setDraft(u,{expires_at:e.target.value})}/></div></div><div className="form-group"><label className="form-label">Reason {d.allowed?'(required)':''}</label><input className="form-input" value={d.reason} onChange={e=>setDraft(u,{reason:e.target.value})} placeholder="Business reason / approval reference"/></div><button className="btn btn-secondary" onClick={()=>saveExternal(u)}><CheckCircle2 size={13}/> Save External Access</button></>}</div>
      </article>})}</div>
    </div>

    {isSuper&&<div className="settings-card"><h2 className="settings-card-title"><ShieldCheck size={18}/> Role Management</h2><div className="setting-help">Built-in roles remain available, but Super Admin can change which portal pages they see. Custom roles inherit a base security role and may only reduce its privileges, never elevate above it.</div>
      <div className="role-admin-grid" style={{marginTop:12}}>{p.portalRoles.map(r=><RoleCard key={r.id} role={r} onSave={saveRole} onDelete={deleteRole}/>)}</div>
      <div className="role-create-box"><h3>Create New Role</h3><div className="settings-grid"><input className="form-input" placeholder="Role name" value={roleName} onChange={e=>setRoleName(e.target.value)}/><select className="form-select" value={roleBase} onChange={e=>setRoleBase(e.target.value as UserRole)}>{Object.entries(baseRoleLabels).map(([k,v])=><option value={k} key={k}>{v} security base</option>)}</select></div><div className="role-check-grid"><div><b>Page Access</b>{(Object.keys(pageLabels) as PageAccessKey[]).map(k=><label className="check-row" key={k}><input type="checkbox" checked={rolePages[k]} disabled={k==='browse'||(roleBase==='super-admin'&&k==='settings')} onChange={e=>setRolePages(x=>({...x,[k]:e.target.checked}))}/>{pageLabels[k]}</label>)}</div><div><b>Permission Limits</b>{Object.keys(permissionLabels).map(k=><label className="check-row" key={k}><input type="checkbox" checked={Boolean(rolePermissions[k])} onChange={e=>setRolePermissions(x=>({...x,[k]:e.target.checked}))}/>{permissionLabels[k]}</label>)}</div></div><button className="btn btn-primary" onClick={createRole}><Plus size={14}/> Create Custom Role</button></div>
    </div>}

    <div className="settings-card"><h2 className="settings-card-title"><Users size={18}/> User Groups</h2><div className="setting-help">Create a department group, assign a role to it, then add users. Adding a member can immediately apply the group role; you can also re-apply the group role to all active members later.</div><div className="settings-grid" style={{marginTop:12}}><input className="form-input" placeholder="Group name" value={groupName} onChange={e=>setGroupName(e.target.value)}/><input className="form-input" placeholder="Description" value={groupDescription} onChange={e=>setGroupDescription(e.target.value)}/><select className="form-select" disabled={!isSuper} value={groupDept} onChange={e=>setGroupDept(e.target.value)}><option value="">Cross-department / global group</option>{activeDepartments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><select className="form-select" value={groupRole} onChange={e=>setGroupRole(e.target.value)}><option value="">No role assignment</option>{manageableRoles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></div><button className="btn btn-primary" style={{marginTop:10}} onClick={createGroup}>Create Group</button>
      <div className="group-admin-grid">{p.userGroups.map(g=>{const candidates=p.users.filter(u=>(!g.department_id||u.department_id===g.department_id)&&!(g.members||[]).some(m=>m.id===u.id));return <div className="group-admin-card" key={g.id}><div className="setting-row"><div><b>{g.name}</b><div className="setting-help">{g.department?.name||'Global'} · Role: {g.portal_role?.name||'None'} · {(g.members||[]).length} member(s)</div></div><button className="icon-btn danger" onClick={()=>deleteGroup(g)}><Trash2 size={15}/></button></div><div className="group-members">{(g.members||[]).map(m=><span className="group-member-chip" key={m.id}>{m.name}<button onClick={()=>removeGroupMember(g,m)}>×</button></span>)}</div><div style={{display:'flex',gap:7,marginTop:8}}><select className="form-select" value={groupMember[g.id]||''} onChange={e=>setGroupMember(x=>({...x,[g.id]:e.target.value}))}><option value="">Add user…</option>{candidates.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><button className="btn btn-secondary" onClick={()=>addGroupMember(g)}>Add</button></div>{g.portal_role_id&&<button className="btn btn-secondary" style={{marginTop:8}} onClick={()=>applyGroupRole(g)}><RefreshCcw size={13}/> Apply Group Role to Members</button>}</div>})}</div>
    </div>
  </div>
}

function RoleCard({role,onSave,onDelete}:{role:PortalRole;onSave:(r:PortalRole,p:Partial<PortalRole>)=>void;onDelete:(r:PortalRole)=>void}){
  const [name,setName]=useState(role.name),[pages,setPages]=useState({...role.page_access}),[permissions,setPermissions]=useState({...role.permissions}),[active,setActive]=useState(role.is_active);
  return <div className="role-admin-card"><div className="setting-row"><div><b>{role.name}</b><div className="setting-help">{role.is_builtin?'Built-in':'Custom'} · Base: {baseRoleLabels[role.base_role]}</div></div>{!role.is_builtin&&<button className="icon-btn danger" onClick={()=>onDelete(role)}><Trash2 size={15}/></button>}</div>{!role.is_builtin&&<input className="form-input" value={name} onChange={e=>setName(e.target.value)}/>}<div className="role-check-grid"><div><span className="mini-heading">Pages</span>{(Object.keys(pageLabels) as PageAccessKey[]).map(k=><label className="check-row" key={k}><input type="checkbox" checked={Boolean(pages[k])} disabled={k==='browse'||(role.base_role==='super-admin'&&k==='settings')} onChange={e=>setPages(x=>({...x,[k]:e.target.checked}))}/>{pageLabels[k]}</label>)}</div><div><span className="mini-heading">Permissions</span>{Object.keys(permissionLabels).map(k=><label className="check-row" key={k}><input type="checkbox" checked={Boolean(permissions[k])} onChange={e=>setPermissions(x=>({...x,[k]:e.target.checked}))}/>{permissionLabels[k]}</label>)}</div></div>{!role.is_builtin&&<label className="check-row"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/>Role active</label>}<button className="btn btn-secondary" onClick={()=>onSave(role,{name,page_access:pages,permissions,is_active:role.is_builtin?true:active})}>Save Role</button></div>
}
