<?php
namespace App\Http\Controllers;
use App\Models\MediaCollection;use App\Models\MediaFile;use App\Models\MediaFolder;use App\Services\AuditService;use Illuminate\Http\Request;
class ContentOrganizationController extends Controller {
 private function dept(Request $r,?int $requested=null): int {$u=$r->user();if($u->role==='super-admin')return $requested?:($u->department_id?:abort(422,'Department required.'));return $u->department_id?:abort(422,'Department required.');}
 public function folderStore(Request $r,AuditService $a){$d=$r->validate(['name'=>'required|string|max:120','description'=>'nullable|string|max:1000','parent_id'=>'nullable|integer|exists:media_folders,id','department_id'=>'nullable|integer|exists:departments,id']);$dept=$this->dept($r,$d['department_id']??null);if(!empty($d['parent_id']))abort_unless(MediaFolder::whereKey($d['parent_id'])->where('department_id',$dept)->exists(),422,'Parent folder must be in the same department.');$f=MediaFolder::create(['department_id'=>$dept,'parent_id'=>$d['parent_id']??null,'name'=>$d['name'],'description'=>$d['description']??null,'created_by'=>$r->user()->id]);$a->log($r,'folder.created',$f,'Folder created.');return back()->with('success','Folder created.');}
 public function folderUpdate(Request $r,MediaFolder $folder,AuditService $a){abort_unless($r->user()->role==='super-admin'||$folder->department_id===$r->user()->department_id,403);$d=$r->validate(['name'=>'sometimes|string|max:120','description'=>'nullable|string|max:1000','parent_id'=>'nullable|integer|exists:media_folders,id','is_active'=>'sometimes|boolean']);if(($d['parent_id']??null)===$folder->id)abort(422,'Folder cannot be its own parent.');if(isset($d['parent_id'])){$p=MediaFolder::find($d['parent_id']);abort_unless(!$p||$p->department_id===$folder->department_id,422,'Parent folder mismatch.');for($n=$p;$n;$n=$n->parent)abort_if($n->id===$folder->id,422,'Folder cycle detected.');}$folder->update($d);$a->log($r,'folder.updated',$folder,'Folder updated.');return back();}
 public function folderDelete(Request $r,MediaFolder $folder,AuditService $a){abort_unless($r->user()->role==='super-admin'||$folder->department_id===$r->user()->department_id,403);abort_if($folder->files()->exists()||$folder->children()->exists(),422,'Folder is not empty.');$a->log($r,'folder.deleted',$folder,'Folder deleted.');$folder->delete();return back();}
 public function collectionStore(Request $r,AuditService $a){$d=$r->validate(['name'=>'required|string|max:120','description'=>'nullable|string|max:1000','department_id'=>'nullable|integer|exists:departments,id']);$c=MediaCollection::create(['department_id'=>$this->dept($r,$d['department_id']??null),'name'=>$d['name'],'description'=>$d['description']??null,'created_by'=>$r->user()->id]);$a->log($r,'collection.created',$c,'Collection created.');return back();}
 public function collectionUpdate(Request $r,MediaCollection $collection,AuditService $a){abort_unless($r->user()->role==='super-admin'||$collection->department_id===$r->user()->department_id,403);$collection->update($r->validate(['name'=>'sometimes|string|max:120','description'=>'nullable|string|max:1000','is_active'=>'sometimes|boolean']));$a->log($r,'collection.updated',$collection,'Collection updated.');return back();}
 public function collectionDelete(Request $r,MediaCollection $collection,AuditService $a){abort_unless($r->user()->role==='super-admin'||$collection->department_id===$r->user()->department_id,403);abort_if($collection->files()->exists(),422,'Collection contains assets.');$a->log($r,'collection.deleted',$collection,'Collection deleted.');$collection->delete();return back();}
 public function membership(Request $r,MediaCollection $collection,AuditService $a){abort_unless($r->user()->role==='super-admin'||$collection->department_id===$r->user()->department_id,403);$d=$r->validate(['media_ids'=>'required|array|max:500','media_ids.*'=>'integer|exists:media_files,id']);$ids=MediaFile::whereIn('id',$d['media_ids'])->where('department_id',$collection->department_id)->pluck('id');abort_unless($ids->count()===count(array_unique($d['media_ids'])),422,'All assets must belong to the collection department.');$collection->files()->sync($ids->mapWithKeys(fn($id)=>[$id=>['added_by'=>$r->user()->id]])->all());$a->log($r,'collection.membership.updated',$collection,'Collection membership updated.',['count'=>$ids->count()]);return back();}
 public function related(Request $r,MediaFile $mediaFile,AuditService $a){$d=$r->validate(['related_media_ids'=>'required|array|max:100','related_media_ids.*'=>'integer|exists:media_files,id']);$ids=array_values(array_filter(array_unique($d['related_media_ids']),fn($id)=>(int)$id!==$mediaFile->id));$valid=MediaFile::whereIn('id',$ids)->where('department_id',$mediaFile->department_id)->pluck('id')->all();abort_unless(count($valid)===count($ids),422,'Related assets must be in the same department.');\DB::table('media_related_assets')->where('media_file_id',$mediaFile->id)->delete();foreach($valid as $id)\DB::table('media_related_assets')->insert(['media_file_id'=>$mediaFile->id,'related_media_file_id'=>$id,'relation_type'=>'related','created_by'=>$r->user()->id,'created_at'=>now(),'updated_at'=>now()]);$a->log($r,'media.related.updated',$mediaFile,'Related assets updated.',['count'=>count($valid)]);return back();}
}
