<?php
namespace App\Http\Controllers;
use App\Models\SystemSetting;use App\Models\User;use App\Services\AuditService;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Hash;use Illuminate\Support\Facades\Mail;use Illuminate\Support\Str;use Illuminate\Validation\Rules\Password;use Inertia\Inertia;
class PasswordResetController extends Controller {
 public function requestForm(){return Inertia::render('Auth/ForgotPassword');}
 public function send(Request $r){$d=$r->validate(['email'=>'required|email']);$email=strtolower(trim($d['email']));$u=User::whereRaw('LOWER(email)=?',[$email])->first();if($u&&$u->isActive()){$token=Str::random(64);DB::table('password_reset_tokens')->updateOrInsert(['email'=>$u->email],['token'=>Hash::make($token),'created_at'=>now()]);$url=url('/reset-password/'.$token).'?email='.urlencode($u->email);try{Mail::raw("Reset your Karyalay Portal password: {$url}\nThis link is single-use and expires automatically.",fn($m)=>$m->to($u->email)->subject('Karyalay Portal password reset'));}catch(\Throwable){}}return back()->with('success','If an active account exists for that email, a password-reset link has been sent.');}
 public function resetForm(Request $r,string $token){return Inertia::render('Auth/ResetPassword',['token'=>$token,'email'=>(string)$r->query('email')]);}
 public function reset(Request $r,string $token,AuditService $audit){$min=max(8,(int)(SystemSetting::valueFor('security.auth',[])['password_min_length']??12));$d=$r->validate(['email'=>'required|email','password'=>['required','confirmed',Password::min($min)]]);$u=User::whereRaw('LOWER(email)=?',[strtolower(trim($d['email']))])->firstOrFail();abort_unless($u->isActive(),422,'Account is not active.');$row=DB::table('password_reset_tokens')->where('email',$u->email)->first();$expiry=(int)(SystemSetting::valueFor('security.auth',[])['password_reset_expiry_minutes']??60);abort_unless($row&&$row->created_at&&now()->diffInMinutes($row->created_at)<=max(5,$expiry)&&Hash::check($token,$row->token),422,'Reset link is invalid or expired.');$u->forceFill(['password'=>Hash::make($d['password']),'must_change_password'=>false])->save();DB::table('password_reset_tokens')->where('email',$u->email)->delete();DB::table('sessions')->where('user_id',$u->id)->delete();$audit->log($r,'auth.password-reset',$u,'Password reset completed.');return redirect()->route('login')->with('success','Password changed. Sign in with your new password.');}
}
