<?php
namespace App\Http\Controllers;
use App\Models\ScheduledReport;use App\Models\ScheduledReportRun;use App\Models\User;use App\Services\AuditService;use App\Services\XlsxService;use Illuminate\Http\Request;use Illuminate\Support\Facades\Storage;
class ScheduledReportController extends Controller {
 public function store(Request $r,AuditService $a){$d=$r->validate(['name'=>'required|string|max:120','report_type'=>'required|in:access,activity,notifications','frequency'=>'required|in:weekly,monthly','format'=>'required|in:csv,xlsx','recipient_user_id'=>'required|exists:users,id','department_id'=>'nullable|exists:departments,id','filters'=>'nullable|array']);$recipient=User::findOrFail($d['recipient_user_id']);abort_unless($recipient->isActive(),422,'Recipient must be active.');$sr=ScheduledReport::create($d+['created_by'=>$r->user()->id,'next_run_at'=>$d['frequency']==='weekly'?now()->addWeek():now()->addMonth()]);$a->log($r,'report.schedule.created',$sr,'Scheduled report created.');return back();}
 public function update(Request $r,ScheduledReport $scheduledReport,AuditService $a){$scheduledReport->update($r->validate(['name'=>'sometimes|string|max:120','is_active'=>'sometimes|boolean','frequency'=>'sometimes|in:weekly,monthly','format'=>'sometimes|in:csv,xlsx','recipient_user_id'=>'sometimes|exists:users,id','department_id'=>'nullable|exists:departments,id','filters'=>'nullable|array']));$a->log($r,'report.schedule.updated',$scheduledReport,'Scheduled report updated.');return back();}
 public function destroy(Request $r,ScheduledReport $scheduledReport,AuditService $a){$a->log($r,'report.schedule.deleted',$scheduledReport,'Scheduled report deleted.');$scheduledReport->delete();return back();}
 public function run(Request $r,ScheduledReport $scheduledReport,AuditService $a){$run=$this->execute($scheduledReport);$a->log($r,'report.schedule.ran',$scheduledReport,'Scheduled report run executed.',['run_id'=>$run->id,'status'=>$run->status]);return back()->with('success','Scheduled report run completed.');}
 public function download(Request $r,ScheduledReportRun $run){$report=$run->scheduledReport??ScheduledReport::findOrFail($run->scheduled_report_id);abort_unless($r->user()->role==='super-admin'||$r->user()->id===$report->recipient_user_id,403);abort_unless($run->status==='completed'&&$run->file_path&&Storage::disk('local')->exists($run->file_path),404);return Storage::disk('local')->download($run->file_path);}
 public function execute(ScheduledReport $report): ScheduledReportRun { $run=ScheduledReportRun::create(['scheduled_report_id'=>$report->id,'status'=>'running','started_at'=>now()]);try{$recipient=$report->recipient()->first();abort_unless($recipient&&$recipient->isActive(),422,'Recipient is no longer active.');if($report->department_id && $recipient->role!=='super-admin')abort_unless($recipient->department_id===$report->department_id,403,'Recipient no longer has department scope.');$rows=$this->rows($report,$recipient);$dir='scheduled-reports/'.date('Y/m');Storage::disk('local')->makeDirectory($dir);$name=$dir.'/report-'.$report->id.'-'.date('Ymd-His').'.'.$report->format;$abs=Storage::disk('local')->path($name);if($report->format==='xlsx')app(XlsxService::class)->write(array_keys($rows[0]??['message'=>'No rows']),array_map('array_values',$rows?:[['message'=>'No rows']]),$abs);else{$fp=fopen($abs,'wb');$headers=array_keys($rows[0]??['message'=>'No rows']);fputcsv($fp,$headers);foreach($rows as $row)fputcsv($fp,array_values($row));fclose($fp);} $run->update(['status'=>'completed','file_path'=>$name,'checksum_sha256'=>hash_file('sha256',$abs),'row_count'=>count($rows),'finished_at'=>now()]);$report->update(['last_run_at'=>now(),'next_run_at'=>$report->frequency==='weekly'?now()->addWeek():now()->addMonth()]);}catch(\Throwable $e){$run->update(['status'=>'failed','error'=>$e->getMessage(),'finished_at'=>now()]);}return $run; }
 private function rows(ScheduledReport $r,User $u): array { $q=\App\Models\AuditLog::query()->latest('id')->limit(5000);if($u->role!=='super-admin')$q->where('actor_user_id',$u->id);if($r->department_id)$q->where('actor_department_id',$r->department_id);if($r->report_type==='access')$q->where('event','like','%access%');if($r->report_type==='notifications')$q->where('event','like','%notification%');return $q->get(['id','event','description','actor_user_id','actor_department_id','created_at'])->map(fn($x)=>$x->toArray())->all(); }
}
