<?php
namespace App\Http\Controllers;
use App\Models\SystemSetting;use App\Services\AuditService;use App\Services\TwoFactorService;use Illuminate\Http\Request;use Illuminate\Support\Facades\Crypt;use Illuminate\Support\Facades\Hash;
class TwoFactorController extends Controller {
 public function setup(Request $r,TwoFactorService $totp){$u=$r->user();abort_if($u->two_factor_confirmed_at,422,'Two-factor authentication is already enabled.');$secret=$totp->generateSecret();$r->session()->put('2fa_setup_secret',$secret);$issuer=SystemSetting::valueFor('security.two_factor',['issuer'=>'Karyalay Portal'])['issuer']??'Karyalay Portal';return response()->json(['secret'=>$secret,'otpauth_uri'=>$totp->uri($issuer,$u->email,$secret)]);}
 public function confirm(Request $r,TwoFactorService $totp,AuditService $audit){$d=$r->validate(['code'=>'required|string']);$secret=(string)$r->session()->get('2fa_setup_secret','');abort_unless($secret&&$totp->verify($secret,$d['code']),422,'Invalid verification code.');$codes=$totp->recoveryCodes();$r->user()->forceFill(['two_factor_secret'=>Crypt::encryptString($secret),'two_factor_recovery_codes'=>Crypt::encryptString(json_encode(array_map(fn($c)=>Hash::make($c),$codes))),'two_factor_confirmed_at'=>now()])->save();$r->session()->forget('2fa_setup_secret');$audit->log($r,'security.2fa.enabled',$r->user(),'Two-factor authentication enabled.');return response()->json(['recovery_codes'=>$codes]);}
 public function disable(Request $r,AuditService $audit){$r->validate(['password'=>'required|current_password']);$r->user()->forceFill(['two_factor_secret'=>null,'two_factor_recovery_codes'=>null,'two_factor_confirmed_at'=>null])->save();$audit->log($r,'security.2fa.disabled',$r->user(),'Two-factor authentication disabled.');return back();}
 public function challenge(Request $r,TwoFactorService $totp){$d=$r->validate(['code'=>'required|string']);$u=$r->user();abort_unless($u->two_factor_secret&&$u->two_factor_confirmed_at,422,'2FA is not enabled.');$secret=Crypt::decryptString($u->two_factor_secret);if($totp->verify($secret,$d['code'])){$r->session()->put('2fa_passed_at',time());return back();}$codes=json_decode(Crypt::decryptString($u->two_factor_recovery_codes),true)?:[];foreach($codes as $i=>$hash)if(Hash::check(strtoupper($d['code']),$hash)){unset($codes[$i]);$u->forceFill(['two_factor_recovery_codes'=>Crypt::encryptString(json_encode(array_values($codes)))])->save();$r->session()->put('2fa_passed_at',time());return back();}abort(422,'Invalid 2FA code or recovery code.');}
}
